/**
 * Salesforce Themer — Service Worker (background.js)
 *
 * Responsibilities (post-A2, 2026-04-16):
 *  1. On install/update: warm chrome.storage.local with pre-rendered preset
 *     CSS + favicon SVG files bundled at content/themes/* and content/favicons/*.
 *     No engine invocation — those files are generated by CI from
 *     themes/engine.js and ship as data in the binary.
 *  2. Handle keyboard commands (cycle theme, toggle dark/light).
 *  3. Broadcast theme changes to active Salesforce tabs.
 *  4. Capture viewport screenshots for the Intelligence Layer.
 *
 * Architecture note: the theme engine no longer runs in the service worker.
 * Studio (options.js) loads the engine directly for custom-theme render and
 * writes the resulting CSS + SVG to storage.local at save time. For free-tier
 * presets, CI pre-renders and the service worker just hot-loads the bundled
 * artifacts. See ARCHITECTURE.md §V2.5 Migration A2.
 */

'use strict';


// ─── Theme registry ──────────────────────────────────────────────────────────

// Loaded at startup from themes/themes.json.
// Kept in memory for the lifetime of the service worker.
let THEME_REGISTRY = { themes: [] };

async function loadThemeRegistry() {
  try {
    const url = chrome.runtime.getURL('themes/themes.json');
    const response = await fetch(url);
    if (!response.ok) throw new Error(`HTTP ${response.status}`);
    THEME_REGISTRY = await response.json();
  } catch (err) {
    console.error('[Salesforce Themer] Failed to load theme registry:', err);
  }
}

// ─── Theme sets for keyboard shortcuts ───────────────────────────────────────

function getLightThemeIds() {
  return THEME_REGISTRY.themes.filter(t => t.category === 'light').map(t => t.id);
}

function getDarkThemeIds() {
  return THEME_REGISTRY.themes.filter(t => t.category === 'dark').map(t => t.id);
}

function getAllThemeIds() {
  return THEME_REGISTRY.themes.map(t => t.id);
}

// ─── Preset artifact cache warm ───────────────────────────────────────────────
// Post-A2: presets are pre-rendered by scripts/render-presets.mjs (CI) and
// bundled as data files. Background reads those files into chrome.storage.local
// for zero-flash apply on SF tabs. No engine invocation here — just a file copy.
//
// Custom themes are NOT warmed by background. Studio (options.js) writes their
// rendered CSS + favicon SVG directly to storage.local at save time. If a custom
// theme is missing locally (fresh device with synced customThemes), content.js
// falls back to fetching the rendered CSS from Supabase (Migration B endpoint).

async function _fetchBundled(path) {
  try {
    const res = await fetch(chrome.runtime.getURL(path));
    if (!res.ok) return null;
    return await res.text();
  } catch (_) {
    return null;
  }
}

async function cacheThemeCSS(themeId) {
  if (!themeId || themeId === 'none') return;
  // Custom themes are Studio-managed; background doesn't warm them.
  if (themeId.startsWith('custom-') || themeId.startsWith('theme_')) return;

  const css = await _fetchBundled(`content/themes/${themeId}.css`);
  if (!css) {
    console.warn('[Salesforce Themer] No bundled CSS for preset:', themeId);
    return;
  }
  const faviconSvg = await _fetchBundled(`content/favicons/${themeId}.svg`);
  const updates = { [`themeCSS_${themeId}`]: css };
  if (faviconSvg) updates[`faviconSvg_${themeId}`] = faviconSvg;
  try {
    await chrome.storage.local.set(updates);
  } catch (err) {
    console.error('[Salesforce Themer] Failed to cache preset artifacts for', themeId, err);
  }
}

async function cacheAllThemes() {
  for (const theme of THEME_REGISTRY.themes) {
    await cacheThemeCSS(theme.id);
  }
  // Custom theme artifacts live in storage.local already (written by Studio).
  // If a customTheme in storage.sync has no matching local entries on a fresh
  // device, content.js's Supabase fallback covers it — no background role here.
}

// ─── Install / update handler ─────────────────────────────────────────────────

chrome.runtime.onInstalled.addListener(async (details) => {
  await loadThemeRegistry();

  if (details.reason === 'install') {
    await chrome.storage.sync.set({
      theme: 'connectry',
      autoMode: false,
      lastLightTheme: 'connectry',
      lastDarkTheme: 'connectry-dark',
      orgThemes: {},
      themeScope: 'both',
      effectsVolume: 'medium',
    });
  } else if (details.reason === 'update') {
    // Backfill new defaults for existing installs that predate them.
    // Also drops the legacy effectsConfig key (V3 model uses shipped
    // effects + volume scaling instead of a global config).
    await migrateDefaultsForExistingInstall();
  }

  await migrateCustomThemeEffects();
  await cacheAllThemes();
});

/**
 * One-time backfill for existing installs. Sets sensible defaults for any
 * keys the user has never explicitly configured. Also drops the legacy
 * V2 effectsConfig key — the V3 model uses theme-shipped effects scaled
 * by an effectsVolume knob instead of a global per-effect config.
 */
async function migrateDefaultsForExistingInstall() {
  try {
    const current = await chrome.storage.sync.get([
      'effectsConfig',
      'effectsVolume',
      'themeScope',
      'autoMode',
    ]);
    const updates = {};

    // V3 migration: drop the legacy effectsConfig key. It was a global
    // per-effect config; under V3 this is replaced by per-theme shipped
    // effects + a Volume scaler. Custom themes keep their own snapshot.
    if (current.effectsConfig !== undefined) {
      await chrome.storage.sync.remove('effectsConfig');
    }

    // V3: backfill effectsVolume to 'medium' if missing; normalize legacy
    // values ('default', 'immersive', 'alive', 'none') from pre-v2.7.1
    // installs. The new vocabulary is 'off' | 'subtle' | 'medium' | 'strong'.
    const VOLUME_LEGACY = { default: 'medium', alive: 'medium', immersive: 'strong', none: 'off' };
    if (current.effectsVolume === undefined) {
      updates.effectsVolume = 'medium';
    } else if (VOLUME_LEGACY[current.effectsVolume]) {
      updates.effectsVolume = VOLUME_LEGACY[current.effectsVolume];
    }

    // Scope: backfill missing values to 'both' (the new V1 default — Setup
    // gets themed too out of the box). Never override an explicit user choice.
    if (current.themeScope === undefined) {
      updates.themeScope = 'both';
    }

    // Auto mode: only set if missing — never override a user toggle.
    if (current.autoMode === undefined) {
      updates.autoMode = false;
    }

    if (Object.keys(updates).length) {
      await chrome.storage.sync.set(updates);
      console.log('[Salesforce Themer] Migrated defaults for existing install:', Object.keys(updates));
    }
  } catch (err) {
    console.warn('[Salesforce Themer] Default migration error:', err.message);
  }
}

/**
 * Backfill the `effects` snapshot on existing custom themes that were created
 * before the per-theme effects feature. Each gets its base theme's suggested
 * effects as a starting point. One-way migration — only runs on themes missing
 * the key.
 */
async function migrateCustomThemeEffects() {
  try {
    const { customThemes = [] } = await chrome.storage.sync.get('customThemes');
    if (!customThemes.length) return;

    let migrated = false;
    for (const t of customThemes) {
      if (!t.effects) {
        // Inline seed logic (mirrors initialCustomThemeEffects('basic', basedOn, null))
        t.effects = suggestedEffectsFor(t.basedOn);
        migrated = true;
      }
    }

    if (migrated) {
      await chrome.storage.sync.set({ customThemes });
      console.log('[Salesforce Themer] Migrated custom themes with effects snapshots');
    }
  } catch (err) {
    console.warn('[Salesforce Themer] Migration error:', err.message);
  }
}

/**
 * Return a suggested effects config for a theme ID, inlined here so the
 * service worker doesn't need to import presets.js. Mirrors
 * effects/presets.js THEME_EFFECTS_MAP + EFFECTS_PRESETS.
 */
function suggestedEffectsFor(themeId) {
  const NONE = {
    preset: 'none',
    hoverLift: false, hoverLiftIntensity: 'medium',
    ambientGlow: false, ambientGlowIntensity: 'medium',
    borderEffect: 'none', borderEffectIntensity: 'medium',
    aurora: false, auroraIntensity: 'medium',
    neonFlicker: false, neonFlickerIntensity: 'medium',
    particles: false, particlesIntensity: 'medium',
    cursorTrail: false, cursorTrailIntensity: 'medium',
  };
  const SUBTLE = { ...NONE, preset: 'subtle', hoverLift: true, hoverLiftIntensity: 'subtle' };
  const ALIVE = {
    ...NONE, preset: 'alive',
    hoverLift: true, hoverLiftIntensity: 'medium',
    ambientGlow: true, ambientGlowIntensity: 'medium',
    borderEffect: 'shimmer', borderEffectIntensity: 'medium',
  };
  const IMMERSIVE = {
    ...NONE, preset: 'immersive',
    hoverLift: true, hoverLiftIntensity: 'strong',
    ambientGlow: true, ambientGlowIntensity: 'strong',
    borderEffect: 'gradient', borderEffectIntensity: 'strong',
    cursorTrail: true, cursorTrailIntensity: 'medium',
  };

  const MAP = {
    'connectry': SUBTLE,
    'connectry-dark': { ...SUBTLE, ambientGlow: true, ambientGlowIntensity: 'subtle' },
    'slate': SUBTLE,
    'tron': { ...IMMERSIVE, neonFlicker: true, neonFlickerIntensity: 'strong', ambientGlow: true, ambientGlowIntensity: 'strong' },
    'obsidian': { ...SUBTLE, ambientGlow: true, ambientGlowIntensity: 'subtle' },
    'graphite': SUBTLE,
    'arctic': { ...ALIVE, aurora: true, auroraIntensity: 'medium', particles: 'snow', particlesIntensity: 'medium' },
    'sakura': { ...SUBTLE, borderEffect: 'shimmer', borderEffectIntensity: 'subtle' },
    'boardroom': SUBTLE,
    'carbon': SUBTLE,
    'nord': { ...SUBTLE, aurora: true, auroraIntensity: 'subtle' },
    'high-contrast': NONE,
    'dracula': { ...SUBTLE, ambientGlow: true, ambientGlowIntensity: 'medium', borderEffect: 'shimmer', borderEffectIntensity: 'medium' },
  };

  return MAP[themeId] || NONE;
}

// Re-generate CSS when browser starts
chrome.runtime.onStartup.addListener(async () => {
  await loadThemeRegistry();
  await migrateCustomThemeEffects();
  await cacheAllThemes();
});

// Also regenerate on any service worker activation (covers extension refresh during dev)
(async () => {
  try {
    await loadThemeRegistry();
    await migrateCustomThemeEffects();
    await cacheAllThemes();
  } catch (_) {}
})();

// ─── Storage change handler ───────────────────────────────────────────────────

chrome.storage.onChanged.addListener(async (changes, area) => {
  if (area !== 'sync') return;
  if (changes.theme?.newValue) {
    // Ensure changed theme is cached (usually already is, but handles edge cases)
    if (!THEME_REGISTRY.themes.length) await loadThemeRegistry();
    await cacheThemeCSS(changes.theme.newValue);
  }
  if (changes.effectsVolume || changes.customThemes) {
    // Broadcast effects update to active SF tabs.
    // - effectsVolume change → OOTB themes need to re-resolve their effects
    // - customThemes change → custom theme snapshots may have updated
    broadcastEffectsToActiveTabs();
  }
});

async function broadcastEffectsToActiveTabs() {
  try {
    const tabs = await chrome.tabs.query({ active: true, currentWindow: true });
    for (const tab of tabs) {
      if (!tab.id) continue;
      chrome.tabs.sendMessage(tab.id, { action: 'setEffects' }).catch(() => {});
    }
  } catch (_) {}
}

// ─── Keyboard commands ────────────────────────────────────────────────────────

chrome.commands.onCommand.addListener(async (command) => {
  if (!THEME_REGISTRY.themes.length) await loadThemeRegistry();

  const allIds = getAllThemeIds();
  const lightIds = new Set(getLightThemeIds());
  const darkIds = new Set(getDarkThemeIds());

  if (command === 'toggle-theme') {
    const result = await chrome.storage.sync.get({ theme: 'connectry', autoMode: false });
    if (result.autoMode) return;
    const idx = allIds.indexOf(result.theme);
    const next = allIds[(idx + 1) % allIds.length];
    await applyAndSaveTheme(next, lightIds, darkIds);
  }

  if (command === 'toggle-diagnostic') {
    const tabs = await chrome.tabs.query({ active: true, currentWindow: true });
    for (const tab of tabs) {
      if (!tab.id) continue;
      chrome.tabs.sendMessage(tab.id, { action: 'toggleDiagnostic' }).catch(() => {});
    }
    return;
  }

  if (command === 'toggle-dark-light') {
    const result = await chrome.storage.sync.get({
      theme: 'connectry',
      lastLightTheme: 'connectry',
      lastDarkTheme: 'connectry-dark',
      autoMode: false,
    });
    if (result.autoMode) return;

    const next = darkIds.has(result.theme)
      ? result.lastLightTheme
      : result.lastDarkTheme;
    await applyAndSaveTheme(next, lightIds, darkIds);
  }
});

async function applyAndSaveTheme(themeId, lightIds, darkIds) {
  const updates = { theme: themeId };
  if (lightIds.has(themeId)) updates.lastLightTheme = themeId;
  else if (darkIds.has(themeId)) updates.lastDarkTheme = themeId;
  await chrome.storage.sync.set(updates);
  await cacheThemeCSS(themeId);
  await broadcastThemeToActiveTabs(themeId);
}

async function broadcastThemeToActiveTabs(themeId) {
  try {
    const tabs = await chrome.tabs.query({ active: true, currentWindow: true });
    for (const tab of tabs) {
      if (!tab.id) continue;
      chrome.tabs.sendMessage(tab.id, { action: 'setTheme', theme: themeId }).catch(() => {});
    }
  } catch (_) {}
}

// ─── Connectry Intelligence Layer — screenshot capture ────────────────────────
// Content scripts can't call chrome.tabs.captureVisibleTab. Diagnostic panel
// posts { action: 'intel.captureScreenshot' } and we return a base64 PNG of
// the visible viewport for the active tab.

// Intel Layer — screenshot capture. (themer.renderAndCacheTheme handler was
// removed in A2: Studio renders locally and writes to storage.local directly,
// so no message round-trip is needed.)
chrome.runtime.onMessage.addListener((msg, sender, sendResponse) => {
  if (msg?.action === 'intel.captureScreenshot') {
    const windowId = sender.tab?.windowId;
    chrome.tabs.captureVisibleTab(windowId, { format: 'png' })
      .then((dataUrl) => sendResponse({ ok: true, dataUrl }))
      .catch((err) => sendResponse({ ok: false, error: String(err) }));
    return true; // async response
  }
  // Open the interactive report in a new tab. Content script can't reliably
  // navigate to chrome-extension:// URLs (user-gesture lost across awaits
  // and some blob: CSP carry-over), so we delegate to the background worker
  // which has full tab APIs.
  if (msg?.action === 'openReportTab' && msg.reportId) {
    // getURL doesn't parse query strings — build it separately.
    const base = chrome.runtime.getURL('diagnostic/report.html');
    const url = `${base}?id=${encodeURIComponent(msg.reportId)}`;
    chrome.tabs.create({ url })
      .then(() => sendResponse({ ok: true }))
      .catch((err) => {
        console.error('[SFT bg] openReportTab failed:', err);
        sendResponse({ ok: false, error: String(err) });
      });
    return true;
  }
  return false;
});
