/**
 * Salesforce Themer — Service Worker (background.js)
 *
 * Responsibilities:
 *  1. On install/update: generate CSS for all themes via the engine and
 *     pre-cache into chrome.storage.local for zero-flash loading.
 *  2. Handle keyboard commands (cycle theme, toggle dark/light).
 *  3. Broadcast theme changes to active Salesforce tabs.
 *
 * Architecture note: the engine runs here (in the service worker) so that
 * content.js stays simple — it only reads pre-cached CSS strings from local
 * storage and injects them. No module imports needed in content scripts.
 */

'use strict';

// ─── Inline: theme engine ────────────────────────────────────────────────────
// The engine is duplicated here (not imported) because MV3 service workers
// don't support importScripts with relative paths in all Chrome versions.
// Keep in sync with themes/engine.js.

function generateThemeCSS(theme) {
  const c = theme.colors;
  const isDark = c.colorScheme === 'dark';
  const fx = c.specialEffects || null;

  const accentRgb = hexToRgb(c.accent) || '74, 111, 165';

  return `
/* Auto-generated by Salesforce Themer engine — theme: ${theme.id} */

/* ─── CSS Custom Properties ─────────────────────────────────────────────── */

:root {
  color-scheme: ${c.colorScheme};

  /* Legacy LWC tokens */
  --lwc-colorBackground: ${c.background} !important;
  --lwc-colorBackgroundAlt: ${c.surface} !important;
  --lwc-colorBackgroundRow: ${c.surface} !important;
  --lwc-colorBackgroundRowHover: ${c.surfaceHover} !important;
  --lwc-colorBackgroundHighlight: ${c.surfaceHighlight} !important;
  --lwc-colorBackgroundSelection: ${c.surfaceSelection} !important;
  --lwc-colorBackgroundButtonBrand: ${c.buttonBrandBg} !important;
  --lwc-colorBackgroundButtonBrandHover: ${c.buttonBrandHover} !important;
  --lwc-colorBackgroundButtonBrandActive: ${c.accentActive} !important;
  --lwc-colorBackgroundButtonDefault: ${c.buttonNeutralBg} !important;
  --lwc-colorBackgroundButtonDefaultHover: ${c.buttonNeutralHover} !important;
  --lwc-headerColorBackground: ${c.nav} !important;
  --lwc-pageColorBackground: ${c.background} !important;
  --lwc-colorTextDefault: ${c.textPrimary} !important;
  --lwc-colorTextWeak: ${c.textSecondary} !important;
  --lwc-colorTextLabel: ${c.textSecondary} !important;
  --lwc-colorTextPlaceholder: ${c.textPlaceholder} !important;
  --lwc-colorTextButtonBrand: ${c.buttonBrandText} !important;
  --lwc-colorTextLink: ${c.link} !important;
  --lwc-colorTextLinkHover: ${c.linkHover} !important;
  --lwc-colorBorder: ${c.border} !important;
  --lwc-colorBorderSeparator: ${c.borderSeparator} !important;
  --lwc-colorBorderInput: ${c.borderInput} !important;
  --lwc-colorBorderInputActive: ${c.accent} !important;
  --lwc-brandPrimary: ${c.accent} !important;
  --lwc-brandPrimaryActive: ${c.accentHover} !important;
  --lwc-brandPrimaryTransparent: ${c.accentLight} !important;
  --lwc-brandAccessible: ${c.accent} !important;
  --lwc-brandAccessibleActive: ${c.accentHover} !important;
  --lwc-colorBackgroundSpin: ${c.accent} !important;
  --lwc-shadowOutlineFocus: ${c.focusRing} !important;

  /* SLDS 2 global tokens */
  --slds-g-color-surface-1: ${c.background} !important;
  --slds-g-color-surface-2: ${c.surface} !important;
  --slds-g-color-surface-3: ${c.surfaceHover} !important;
  --slds-g-color-surface-4: ${c.border} !important;
  --slds-g-color-on-surface-1: ${c.textPrimary} !important;
  --slds-g-color-on-surface-2: ${c.textSecondary} !important;
  --slds-g-color-on-surface-3: ${c.textMuted} !important;
  --slds-g-color-border-1: ${c.border} !important;
  --slds-g-color-border-2: ${c.borderInput} !important;
  --slds-g-color-brand-1: ${c.accent} !important;
  --slds-g-color-brand-2: ${c.accentHover} !important;
  --slds-g-color-brand-3: ${c.accentActive} !important;
  --slds-g-color-neutral-1: ${c.background} !important;
  --slds-g-color-neutral-2: ${c.surfaceAlt || c.surfaceHover} !important;
  --slds-g-color-neutral-3: ${c.border} !important;

  /* Component hooks */
  --slds-c-card-color-background: ${c.surface} !important;
  --slds-c-card-color-border: ${c.border} !important;
  --slds-c-input-color-background: ${isDark ? c.background : c.surface} !important;
  --slds-c-input-color-border: ${c.borderInput} !important;
  --slds-c-input-color-border-focus: ${c.accent} !important;
  --slds-c-button-brand-color-background: ${c.buttonBrandBg} !important;
  --slds-c-button-brand-color-border: ${c.buttonBrandBorder} !important;
  --slds-c-button-brand-color-background-hover: ${c.buttonBrandHover} !important;
  --slds-c-button-neutral-color-background: ${c.buttonNeutralBg} !important;
  --slds-c-button-neutral-color-border: ${c.buttonNeutralBorder} !important;
}

/* ─── Base ───────────────────────────────────────────────────────────────── */

html,
body,
.desktop {
  background-color: ${c.background} !important;
  color: ${c.textPrimary} !important;${fx && fx.gridOverlay ? `
  background-image:
    repeating-linear-gradient(
      0deg,
      transparent,
      transparent 39px,
      rgba(${hexToRgb(c.accent)}, 0.02) 39px,
      rgba(${hexToRgb(c.accent)}, 0.02) 40px
    ),
    repeating-linear-gradient(
      90deg,
      transparent,
      transparent 39px,
      rgba(${hexToRgb(c.accent)}, 0.02) 39px,
      rgba(${hexToRgb(c.accent)}, 0.02) 40px
    ) !important;
  background-attachment: fixed !important;` : ''}
}

/* ─── Global Header — always white so SF logo/icons remain visible ────── */
${c.globalHeaderWhite ? `
.slds-global-header,
.slds-global-header_container,
.forceSearchDesktopHeader {
  background-color: #ffffff !important;
  color: #2d2d2d !important;
}` : ''}

${isDark || !c.globalHeaderWhite ? `
/* Search box in header — themed for dark or non-white-header themes */
.slds-global-header .slds-input,
.slds-global-header input[type="search"],
.forceSearchDesktopHeader input,
.slds-global-header .slds-form-element__control input {
  background-color: ${c.searchBg || c.surface} !important;
  color: ${c.searchText || c.textPrimary} !important;
  border-color: ${c.searchBorder || c.border} !important;
  border-radius: 6px !important;${fx && fx.glowOnHover ? `
  box-shadow: 0 0 6px ${c.accentLight} !important;` : ''}
}

.slds-global-header .slds-input::placeholder,
.slds-global-header input::placeholder {
  color: ${c.searchPlaceholder || c.textPlaceholder} !important;
}

.slds-global-header .slds-input:focus,
.slds-global-header input:focus {
  border-color: ${c.searchFocusBorder || c.accent} !important;
  box-shadow: ${c.searchFocusShadow || c.focusRing} !important;
}` : ''}

/* ─── Navigation ─────────────────────────────────────────────────────────── */

.oneGlobalNav,
one-app-nav-bar,
.navexConsoleTabBar,
[class*="globalNavigation"],
.slds-context-bar {
  background-color: ${c.nav} !important;
  border-bottom: 1px solid ${c.navBorder} !important;${fx && fx.navBoxShadow ? `
  box-shadow: ${fx.navBoxShadow} !important;` : ''}
}

.slds-context-bar__item,
.navexConsoleTabItem,
.oneConsoleTabItem {
  color: ${c.navText} !important;
}

.slds-context-bar__item:hover,
.navexConsoleTabItem:hover {
  background-color: ${c.navHover} !important;${c.navActiveText !== c.navText ? `
  color: ${c.navActiveText} !important;` : ''}
}

/* Active nav tab — target all SF variations with max specificity */
.slds-context-bar__item.slds-is-active,
.slds-context-bar__item.slds-is-active.slds-is-unsaved,
one-app-nav-bar-item-root.slds-is-active,
one-app-nav-bar-item-root.navItem.slds-is-active,
.navexConsoleTabItem.active {
  background-color: ${c.navActive} !important;
  background: ${c.navActive} !important;
  border-bottom-color: ${c.navActiveBorder} !important;
  border-radius: 0 !important;
  box-shadow: none !important;${fx && fx.navActiveBoxShadow ? `
  box-shadow: ${fx.navActiveBoxShadow} !important;` : ''}
  color: ${c.navActiveText} !important;
}

/* Kill the underline pseudo-elements on active tab */
.slds-context-bar__item.slds-is-active::before,
.slds-context-bar__item.slds-is-active::after,
one-app-nav-bar-item-root.slds-is-active::before,
one-app-nav-bar-item-root.slds-is-active::after,
.slds-context-bar__item.slds-is-active a::before,
.slds-context-bar__item.slds-is-active a::after,
one-app-nav-bar-item-root.slds-is-active a::before,
one-app-nav-bar-item-root.slds-is-active a::after {
  background-color: ${c.navActiveBorder} !important;
  background: ${c.navActiveBorder} !important;
  border-color: ${c.navActiveBorder} !important;
}

/* Active tab inner link — must beat SF's aria-current="page" + pill styling */
.slds-context-bar__item.slds-is-active .slds-context-bar__label-action,
.slds-context-bar__item.slds-is-active a,
one-app-nav-bar-item-root.slds-is-active a,
one-app-nav-bar-item-root.slds-is-active a.dndItem,
one-app-nav-bar-item-root.slds-is-active .slds-context-bar__label-action,
.slds-context-bar a[aria-current="page"] {
  color: ${c.navActiveText} !important;
  background-color: transparent !important;
  background: transparent !important;
  border-color: transparent !important;
  box-shadow: none !important;
  border-radius: 0 !important;
}

/* Nav text and icons */
.slds-context-bar__label-action,
.slds-context-bar__icon-action,
.slds-context-bar .slds-icon {
  color: ${c.navIcon} !important;
  fill: ${c.navIcon} !important;
}

/* App launcher button */
.slds-context-bar__app-name,
.appLauncherButton {
  color: ${c.navAppName} !important;
  border-right: 1px solid ${c.navAppBorder} !important;${fx ? `
  text-shadow: 0 0 8px ${c.accentLight} !important;` : ''}
}

/* App launcher waffle dots — target individual dots, not the container */
.slds-icon-waffle .slds-r1,
.slds-icon-waffle .slds-r2,
.slds-icon-waffle .slds-r3,
.slds-icon-waffle .slds-r4,
.slds-icon-waffle .slds-r5,
.slds-icon-waffle .slds-r6,
.slds-icon-waffle .slds-r7,
.slds-icon-waffle .slds-r8,
.slds-icon-waffle .slds-r9 {
  background-color: ${c.navWaffleDot} !important;
}

/* ─── Main Content ───────────────────────────────────────────────────────── */

.oneContent,
.oneWorkspace,
.flexipageBody,
.onesetupSetupLayout,
.setupcontent {
  background-color: ${fx && fx.gridOverlay ? 'transparent' : c.background} !important;
}

/* ─── Page Headers ───────────────────────────────────────────────────────── */

.slds-page-header,
.forceListViewManager .listViewManager,
[class*="pageHeader"] {
  background-color: ${c.surface} !important;
  border-bottom: 1px solid ${c.border} !important;
  box-shadow: ${isDark ? '0 1px 0 rgba(255, 255, 255, 0.04)' : '0 1px 3px rgba(0, 0, 0, 0.06)'} !important;${fx ? `
  box-shadow: 0 1px 20px rgba(${hexToRgb(c.accent)}, 0.06) !important;` : ''}
}

.slds-page-header__title,
.slds-page-header__name-title {
  color: ${c.textPrimary} !important;${fx ? `
  text-shadow: 0 0 12px rgba(${hexToRgb(c.accent)}, 0.3) !important;` : ''}
}

.slds-page-header__meta-text {
  color: ${c.textSecondary} !important;
}

/* ─── Cards ──────────────────────────────────────────────────────────────── */

/* Cards — border only on .slds-card itself, not inner body/footer */
.slds-card,
.forceRecordCard {
  background-color: ${c.surface} !important;
  border-color: ${c.border} !important;
  box-shadow: ${isDark ? '0 1px 4px rgba(0, 0, 0, 0.2)' : '0 1px 4px rgba(0, 0, 0, 0.06)'} !important;${isDark ? `
  color: ${c.textPrimary} !important;` : ''}${fx ? `
  box-shadow: 0 0 20px rgba(${hexToRgb(c.accent)}, 0.06), inset 0 0 40px rgba(0, 0, 0, 0.2) !important;` : ''}
}

.slds-card__body,
.slds-card__footer {
  background-color: ${c.surface} !important;${isDark ? `
  color: ${c.textPrimary} !important;` : ''}
}
${fx ? `
.slds-card:hover {
  border-color: ${fx.cardHoverBorder} !important;
  box-shadow: ${fx.cardHoverShadow} !important;
}` : ''}

.slds-card__header {
  background-color: ${c.surface} !important;
  border-color: ${c.border} !important;
  border-bottom: 1px solid ${isDark ? 'rgba(255,255,255,0.06)' : c.border} !important;
}

/* ─── Buttons ────────────────────────────────────────────────────────────── */

.slds-button_brand,
.slds-button--brand {
  background-color: ${c.buttonBrandBg} !important;
  border: 1px solid ${c.buttonBrandBorder} !important;
  color: ${c.buttonBrandText} !important;${fx ? `
  text-shadow: 0 0 8px rgba(${hexToRgb(c.accent)}, 0.5) !important;
  box-shadow: 0 0 10px rgba(${hexToRgb(c.accent)}, 0.15), inset 0 0 10px rgba(${hexToRgb(c.accent)}, 0.05) !important;` : ''}
}

.slds-button_brand:hover,
.slds-button--brand:hover {
  background-color: ${c.buttonBrandHover} !important;
  border-color: ${c.buttonBrandHover} !important;${fx ? `
  box-shadow: 0 0 20px rgba(${hexToRgb(c.accent)}, 0.3), inset 0 0 20px rgba(${hexToRgb(c.accent)}, 0.1) !important;` : ''}
}

.slds-button_neutral,
.slds-button--neutral {
  background-color: ${c.buttonNeutralBg} !important;
  border-color: ${c.buttonNeutralBorder} !important;
  color: ${c.buttonNeutralText} !important;
}

.slds-button_neutral:hover,
.slds-button--neutral:hover {
  background-color: ${c.buttonNeutralHover} !important;
}

/* ─── Form Elements ──────────────────────────────────────────────────────── */

.slds-input,
.slds-textarea,
.slds-select,
.slds-combobox__form-element,
.slds-has-input-focus .slds-input {
  background-color: ${isDark ? c.background : c.surface} !important;
  border-color: ${c.borderInput} !important;
  color: ${c.textPrimary} !important;
}

.slds-input:focus,
.slds-textarea:focus,
.slds-select:focus {
  border-color: ${c.accent} !important;
  box-shadow: ${isDark
    ? `0 0 0 3px rgba(${hexToRgb(c.accent)}, 0.2)${fx ? `, 0 0 12px rgba(${hexToRgb(c.accent)}, 0.15)` : ''}`
    : `0 0 0 3px rgba(${hexToRgb(c.accent)}, 0.2)`
  } !important;
  outline: none !important;
}

.slds-input::placeholder,
.slds-textarea::placeholder {
  color: ${c.textPlaceholder} !important;
}

.slds-form-element__label {
  color: ${c.textSecondary} !important;
  font-weight: 500 !important;
}

/* ─── Tables ─────────────────────────────────────────────────────────────── */

.slds-table {
  background-color: ${c.surface} !important;
  border: 1px solid ${c.border} !important;
}

.slds-table thead th,
.slds-table thead td {
  background-color: ${c.tableHeaderBg} !important;
  color: ${c.tableHeaderText} !important;
  border-bottom: ${isDark ? '2px' : '2px'} solid ${c.border} !important;
  font-weight: 600 !important;${fx ? `
  text-transform: uppercase !important;
  font-size: 11px !important;
  letter-spacing: 0.08em !important;
  text-shadow: 0 0 8px rgba(${hexToRgb(c.accent)}, 0.4) !important;` : ''}
}

.slds-table tbody tr {
  background-color: ${c.surface} !important;
  border-bottom: 1px solid ${c.tableBorderRow} !important;
  color: ${c.textPrimary} !important;
}

.slds-table tbody tr:nth-child(even) {
  background-color: ${c.tableAltRow} !important;
}

.slds-table tbody tr:hover {
  background-color: ${c.tableHoverRow} !important;${fx ? `
  box-shadow: inset 0 0 20px rgba(${hexToRgb(c.accent)}, 0.04) !important;` : ''}
}

.slds-table td,
.slds-table th {
  color: ${c.textPrimary} !important;
  border-right: 1px solid ${c.tableColBorder} !important;
}

/* ─── Modals ─────────────────────────────────────────────────────────────── */

.slds-modal__container {
  background-color: ${c.modalBg} !important;
  border: 1px solid ${c.border} !important;
  box-shadow: ${c.modalShadow} !important;
}

.slds-modal__header {
  background-color: ${c.modalHeaderBg} !important;
  border-bottom: 1px solid ${c.border} !important;
  color: ${c.textPrimary} !important;
}

.slds-modal__content {
  background-color: ${c.modalBg} !important;
  color: ${c.textPrimary} !important;
}

.slds-modal__footer {
  background-color: ${c.modalFooterBg} !important;
  border-top: 1px solid ${c.border} !important;
}

.slds-backdrop {
  background-color: ${c.modalBackdrop} !important;${fx ? `
  backdrop-filter: blur(2px) !important;` : ''}
}

/* ─── Dropdowns & Popovers ───────────────────────────────────────────────── */

.slds-dropdown,
.slds-dropdown__list {
  background-color: ${c.dropdownBg} !important;
  border: 1px solid ${c.border} !important;
  box-shadow: ${isDark ? '0 8px 24px rgba(0, 0, 0, 0.5)' : '0 4px 16px rgba(0, 0, 0, 0.10)'} !important;${fx ? `
  box-shadow: 0 0 30px rgba(${hexToRgb(c.accent)}, 0.12), 0 8px 24px rgba(0, 0, 0, 0.6) !important;` : ''}
}

.slds-dropdown__item > a,
.slds-dropdown__item > span {
  color: ${c.textPrimary} !important;
}

.slds-dropdown__item:hover > a,
.slds-dropdown__item:hover > span,
.slds-dropdown__item:focus > a {
  background-color: ${c.dropdownItemHoverBg} !important;
  color: ${c.dropdownItemHoverText} !important;
}

.slds-popover {
  background-color: ${c.dropdownBg} !important;
  border: 1px solid ${c.border} !important;
  box-shadow: ${isDark ? '0 8px 24px rgba(0, 0, 0, 0.45)' : '0 4px 16px rgba(0, 0, 0, 0.10)'} !important;
  color: ${c.textPrimary} !important;
}

/* ─── Tabs ───────────────────────────────────────────────────────────────── */

.slds-tabs_default__nav,
.slds-tabs--default__nav {
  border-bottom: 2px solid ${c.tabNavBorder} !important;
  background-color: transparent !important;
}

.slds-tabs_default__item,
.slds-tabs--default__item {
  color: ${c.tabInactiveColor} !important;
}

.slds-tabs_default__item.slds-is-active,
.slds-tabs--default__item.slds-active {
  color: ${c.tabActiveColor} !important;
  border-bottom-color: ${c.tabActiveBorder} !important;${fx ? `
  text-shadow: 0 0 10px rgba(${hexToRgb(c.accent)}, 0.5) !important;` : ''}
}

/* Override SF's ::after pseudo-element tab indicator */
.slds-tabs_default__item.slds-is-active::after,
.slds-tabs--default__item.slds-active::after {
  background-color: ${c.tabActiveBorder} !important;
}

.slds-tabs_default__content,
.slds-tabs--default__content {
  background-color: ${c.tabContentBg} !important;
}

/* ─── Pills & Badges ─────────────────────────────────────────────────────── */

.slds-pill {
  background-color: ${c.pillBg} !important;
  border: 1px solid ${c.pillBorder} !important;
  color: ${c.pillText} !important;
}

.slds-badge {
  background-color: ${c.badgeBg} !important;
  color: ${c.badgeText} !important;${c.badgeBorder !== 'none' ? `
  border: ${c.badgeBorder} !important;` : ''}${fx ? `
  text-shadow: 0 0 6px rgba(${hexToRgb(c.accent)}, 0.5) !important;` : ''}
}

/* ─── Scrollbars ─────────────────────────────────────────────────────────── */

::-webkit-scrollbar {
  width: ${fx ? '6px' : '8px'} !important;
  height: ${fx ? '6px' : '8px'} !important;
}

::-webkit-scrollbar-track {
  background: ${c.scrollTrack} !important;${fx ? `
  border-left: 1px solid rgba(${hexToRgb(c.accent)}, 0.06) !important;` : ''}
}

::-webkit-scrollbar-thumb {
  background: ${c.scrollThumb} !important;
  border-radius: ${fx ? '3px' : '4px'} !important;
}

::-webkit-scrollbar-thumb:hover {
  background: ${c.scrollThumbHover} !important;${fx && fx.glowOnHover ? `
  box-shadow: 0 0 6px rgba(${hexToRgb(c.accent)}, 0.3) !important;` : ''}
}

/* ─── Record Detail ──────────────────────────────────────────────────────── */

.forceOutputField,
.slds-form-element__static {
  color: ${c.textPrimary} !important;
}

/* ─── Sidebar / Panel ────────────────────────────────────────────────────── */

.slds-panel,
.slds-split-view_container {
  background-color: ${c.panelBg} !important;
  border-right: 1px solid ${c.panelBorder} !important;
}

/* ─── Links ──────────────────────────────────────────────────────────────── */

a,
.slds-truncate a,
.forceOutputLookup a {
  color: ${c.link} !important;${fx && fx.linkTextShadow ? `
  text-shadow: ${fx.linkTextShadow} !important;` : ''}
}

a:hover {
  color: ${c.linkHover} !important;${fx && fx.linkHoverTextShadow ? `
  text-shadow: ${fx.linkHoverTextShadow} !important;` : ''}
}

/* ─── Setup Pages ────────────────────────────────────────────────────────── */

.setupcontent,
.slds-setup-assistant,
.setup-page,
[class*="setupLayout"],
.onesetupSetupLayout,
.setupTabContent,
.slds-setup-summary,
.forceSetupDesktop {
  background-color: ${c.background} !important;
  color: ${c.textPrimary} !important;
}

/* ─── Reports ────────────────────────────────────────────────────────────── */

.report-container,
.reportOutput,
[class*="reportPage"],
.slds-report,
.forceReportOutput,
.reportHeader {
  background-color: ${c.background} !important;
  color: ${c.textPrimary} !important;
}

/* ─── Console / Service Console ──────────────────────────────────────────── */

.navexConsoleContent,
.workspaceManager,
.split-view,
.slds-split-view,
[class*="console"] {
  background-color: ${c.background} !important;
  color: ${c.textPrimary} !important;
}

/* ─── Record Page Header / Highlights ────────────────────────────────────── */

.highlights,
.forceHighlightsStencilDesktop,
.forceRecordLayout,
.forceHighlightsPanel,
.slds-page-header--record-home,
.slds-page-header_record-home,
.flexipageHeader,
.record-page-decorator,
.recordHomeTemplate,
.forceHighlightsLayout {
  background-color: ${c.background} !important;
  color: ${c.textPrimary} !important;
  border-color: ${c.border} !important;
  box-shadow: ${isDark ? '0 1px 3px rgba(0, 0, 0, 0.15)' : '0 1px 3px rgba(0, 0, 0, 0.06)'} !important;
}

/* Record page full body background */
.flexipagePage,
.flexipage-template,
.uiTabBar + .tabContent,
.forceRecordFlexiPage {
  background-color: ${c.background} !important;
}

/* ─── Path / Stage Path ─────────────────────────────────────────────────── */

/* Path structural containers — recolor, keep structure */
.slds-path,
.slds-path__scroller,
.slds-path__track,
.slds-path__wrap,
.slds-path__coach,
.slds-path__nav,
.slds-path__scroller-container,
.slds-path__scroller_inner,
.slds-path__scroll-controls,
.slds-grid.slds-path__track,
.pathAssistantContainer,
.forcePathAssistant,
lightning-sales-path,
records-lwc-highlights-panel,
.runtime_sales_pathassistantPathAssistantTabSet,
.runtime_sales_pathassistantPathAssistantHeader,
.uiScroller.slds-path__scroller,
[class*="pathAssistant"],
[class*="PathAssistant"],
[class*="salesPath"],
[class*="SalesPath"] {
  background-color: ${c.surface} !important;
  color: ${c.textPrimary} !important;
}

/* Path scroller inner wrapper */
.slds-path__scroller .scroller,
.slds-path__scroller .slds-path__scroller_inner {
  background-color: ${c.surface} !important;
}

/* The slds-card wrapping the path — recolor, keep structure */
body .pathOriginal .slds-card,
body .pathOriginal .slds-card__body,
body .pathOriginal .slds-card__body_inner,
body .runtime_sales_pathassistantPathAssistant .slds-card,
body .runtime_sales_pathassistantPathAssistant .slds-card__body,
body .runtime_sales_pathassistantPathAssistant .slds-card__body_inner,
body .runtime_sales_pathassistantPathAssistant > article,
body .forcePathAssistant .slds-card,
body .forcePathAssistant .slds-card__body,
body .forcePathAssistant .slds-card__body_inner {
  background-color: ${c.surface} !important;
  border-color: ${c.border} !important;
  box-shadow: ${isDark ? '0 1px 4px rgba(0, 0, 0, 0.2)' : '0 1px 4px rgba(0, 0, 0, 0.06)'} !important;
}

/* Path items — boosted specificity with body prefix */
body .slds-path__item,
body .slds-path__item .slds-path__link,
body .slds-path__item a.slds-path__link {
  background-color: ${c.surfaceAlt} !important;
}

body .slds-path__item.slds-is-complete,
body .slds-path__item.slds-is-complete .slds-path__link,
body .slds-path__item.slds-is-complete a.slds-path__link {
  background-color: ${c.accent} !important;
}

body .slds-path__item.slds-is-current,
body .slds-path__item.slds-is-current .slds-path__link,
body .slds-path__item.slds-is-current a.slds-path__link {
  background-color: ${c.accent} !important;
}

body .slds-path__item.slds-is-incomplete,
body .slds-path__item.slds-is-incomplete .slds-path__link,
body .slds-path__item.slds-is-incomplete a.slds-path__link {
  background-color: ${c.surfaceAlt} !important;
}

/* Path chevrons — SLDS uses skewed ::before/::after with background, NOT border triangles */
/* Each state must set background on BOTH the item AND its pseudo-elements */

/* Incomplete (default) — item + pseudo-elements */
body .slds-path__item::before,
body .slds-path__item::after {
  background: ${c.surfaceAlt} !important;
}

body .slds-path__item.slds-is-incomplete::before,
body .slds-path__item.slds-is-incomplete::after {
  background: ${c.surfaceAlt} !important;
}

/* Complete */
body .slds-path__item.slds-is-complete::before,
body .slds-path__item.slds-is-complete::after {
  background: ${c.accent} !important;
}

/* Current */
body .slds-path__item.slds-is-current::before,
body .slds-path__item.slds-is-current::after {
  background-color: ${c.accent} !important;
  background-image: none !important;
}

/* Active / selected — MUST come after incomplete to win specificity */
/* Handles both .slds-is-active alone AND .slds-is-incomplete.slds-is-active */
body .slds-path__item.slds-is-active,
body .slds-path__item.slds-is-active .slds-path__link,
body .slds-path__item.slds-is-active a.slds-path__link,
body .slds-path__item.slds-is-incomplete.slds-is-active,
body .slds-path__item.slds-is-incomplete.slds-is-active .slds-path__link,
body .slds-path__item.slds-is-incomplete.slds-is-active a.slds-path__link,
body .slds-path__item [aria-selected="true"] {
  background-color: ${c.accentHover} !important;
  color: ${c.buttonBrandText} !important;
}

body .slds-path__item.slds-is-active::before,
body .slds-path__item.slds-is-active::after,
body .slds-path__item.slds-is-incomplete.slds-is-active::before,
body .slds-path__item.slds-is-incomplete.slds-is-active::after {
  background: ${c.accentHover} !important;
}

/* Hover — incomplete items */
.slds-path__item:hover,
.slds-path__item:hover .slds-path__link {
  background-color: ${c.surfaceHover} !important;
}

.slds-path__item:hover::before,
.slds-path__item:hover::after {
  background: ${c.surfaceHover} !important;
}

/* Hover — complete/current items */
.slds-path__item.slds-is-complete:hover,
.slds-path__item.slds-is-complete:hover .slds-path__link,
.slds-path__item.slds-is-current:hover,
.slds-path__item.slds-is-current:hover .slds-path__link {
  background-color: ${c.accentHover} !important;
}

.slds-path__item.slds-is-complete:hover::before,
.slds-path__item.slds-is-complete:hover::after,
.slds-path__item.slds-is-current:hover::before,
.slds-path__item.slds-is-current:hover::after {
  background: ${c.accentHover} !important;
}

/* Path text colors */
.slds-path__title {
  color: ${c.textPrimary} !important;
}

.slds-path__item.slds-is-complete .slds-path__title,
.slds-path__item.slds-is-current .slds-path__title,
.slds-path__item.slds-is-active .slds-path__title {
  color: ${c.buttonBrandText} !important;
}

/* Path stage icon (checkmark on completed) */
.slds-path__stage {
  color: ${c.buttonBrandText} !important;
}

/* ─── Related List Cards (right sidebar) ─────────────────────────────────── */

/* Related list containers — background only, cards handle their own borders */
.forceRelatedListContainer,
.forceRelatedListSingleContainer {
  background-color: ${c.background} !important;
}

/* Related list inner headers — no extra borders */
.slds-page-header_joined,
.slds-page-header_bleed,
.slds-page-header.slds-page-header_joined {
  border-color: transparent !important;
  box-shadow: none !important;
}

/* ─── Profile Icon / Global Actions (top right) ─────────────────────────── */
/* Keep white header's action icons visible — don't override their colors */

.slds-global-actions__item > button,
.slds-global-actions__item > span,
.slds-global-actions__item > div > button {
  background-color: transparent !important;
}

${c.globalHeaderWhite ? `
/* Header stays white — ensure icons are dark/visible, not washed out */
.slds-global-header .slds-global-header__icon,
.slds-global-header .slds-button__icon,
.slds-global-header .forceIcon .slds-icon,
.slds-global-actions .slds-icon {
  fill: #54698d !important;
  color: #54698d !important;
}` : ''}

/* Profile avatar container */
.slds-avatar,
.forceSocialPhoto,
.photoContainer {
  border: none !important;
  box-shadow: none !important;
}
`;
}

/**
 * Convert hex color to "R, G, B" string for use in rgba().
 * Returns a fallback string if parsing fails.
 * @param {string} hex
 * @returns {string}
 */
function hexToRgb(hex) {
  if (!hex || typeof hex !== 'string') return '74, 111, 165';
  // Strip leading # and handle short hex
  const clean = hex.replace('#', '');
  if (clean.length === 3) {
    const r = parseInt(clean[0] + clean[0], 16);
    const g = parseInt(clean[1] + clean[1], 16);
    const b = parseInt(clean[2] + clean[2], 16);
    return `${r}, ${g}, ${b}`;
  }
  if (clean.length === 6) {
    const r = parseInt(clean.slice(0, 2), 16);
    const g = parseInt(clean.slice(2, 4), 16);
    const b = parseInt(clean.slice(4, 6), 16);
    return `${r}, ${g}, ${b}`;
  }
  return '74, 111, 165';
}

// ─── Inline: derivation engine ─────────────────────────────────────────────
// Inlined from themes/derive.js — keep in sync.
// Uses _ prefixed color utils to avoid conflict with hexToRgb above.


// Color utilities — inlined here for service worker compatibility (no imports).
// Canonical source: themes/color-utils.js

function _parseColor(color) {
  if (!color || typeof color !== 'string') return null;
  color = color.trim();
  if (color[0] === '#') {
    const hex = color.slice(1);
    if (hex.length === 3) {
      return { r: parseInt(hex[0] + hex[0], 16), g: parseInt(hex[1] + hex[1], 16), b: parseInt(hex[2] + hex[2], 16) };
    }
    if (hex.length >= 6) {
      return { r: parseInt(hex.slice(0, 2), 16), g: parseInt(hex.slice(2, 4), 16), b: parseInt(hex.slice(4, 6), 16) };
    }
  }
  const m = color.match(/rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)/);
  if (m) return { r: +m[1], g: +m[2], b: +m[3] };
  return null;
}

function _rgbToHex(r, g, b) {
  const c = (v) => Math.max(0, Math.min(255, Math.round(v))).toString(16).padStart(2, '0');
  return '#' + c(r) + c(g) + c(b);
}

function _rgbToHsl(r, g, b) {
  r /= 255; g /= 255; b /= 255;
  const max = Math.max(r, g, b), min = Math.min(r, g, b);
  const l = (max + min) / 2;
  let h = 0, s = 0;
  if (max !== min) {
    const d = max - min;
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    if (max === r) h = ((g - b) / d + (g < b ? 6 : 0)) / 6;
    else if (max === g) h = ((b - r) / d + 2) / 6;
    else h = ((r - g) / d + 4) / 6;
  }
  return { h: h * 360, s: s * 100, l: l * 100 };
}

function _hslToRgb(h, s, l) {
  h /= 360; s /= 100; l /= 100;
  if (s === 0) { const v = Math.round(l * 255); return { r: v, g: v, b: v }; }
  const hue2rgb = (p, q, t) => {
    if (t < 0) t += 1; if (t > 1) t -= 1;
    if (t < 1/6) return p + (q-p) * 6 * t;
    if (t < 1/2) return q;
    if (t < 2/3) return p + (q-p) * (2/3 - t) * 6;
    return p;
  };
  const q = l < 0.5 ? l * (1+s) : l + s - l*s;
  const p = 2*l - q;
  return {
    r: Math.round(hue2rgb(p, q, h + 1/3) * 255),
    g: Math.round(hue2rgb(p, q, h) * 255),
    b: Math.round(hue2rgb(p, q, h - 1/3) * 255),
  };
}

function _lighten(hex, amount) {
  const c = _parseColor(hex); if (!c) return hex;
  const hsl = _rgbToHsl(c.r, c.g, c.b);
  hsl.l = Math.min(100, hsl.l + amount);
  const rgb = _hslToRgb(hsl.h, hsl.s, hsl.l);
  return _rgbToHex(rgb.r, rgb.g, rgb.b);
}

function _darken(hex, amount) {
  const c = _parseColor(hex); if (!c) return hex;
  const hsl = _rgbToHsl(c.r, c.g, c.b);
  hsl.l = Math.max(0, hsl.l - amount);
  const rgb = _hslToRgb(hsl.h, hsl.s, hsl.l);
  return _rgbToHex(rgb.r, rgb.g, rgb.b);
}

function _alpha(hex, opacity) {
  const c = _parseColor(hex); if (!c) return hex;
  return `rgba(${c.r}, ${c.g}, ${c.b}, ${opacity})`;
}

function _contrast(hex) {
  const c = _parseColor(hex); if (!c) return '#ffffff';
  const [rs, gs, bs] = [c.r, c.g, c.b].map(v => {
    v /= 255;
    return v <= 0.03928 ? v / 12.92 : Math.pow((v + 0.055) / 1.055, 2.4);
  });
  return (0.2126*rs + 0.7152*gs + 0.0722*bs) > 0.35 ? '#1a1a1a' : '#ffffff';
}

function _mix(hex1, hex2, weight) {
  const c1 = _parseColor(hex1), c2 = _parseColor(hex2);
  if (!c1 || !c2) return hex1;
  const w = Math.max(0, Math.min(1, weight));
  return _rgbToHex(c1.r+(c2.r-c1.r)*w, c1.g+(c2.g-c1.g)*w, c1.b+(c2.b-c1.b)*w);
}

// ─── Derivation Engine ───────────────────────────────────────────────────────

/**
 * The 23 core keys that users set directly.
 * Everything else is derived from these.
 */
const CORE_KEYS = [
  'colorScheme', 'background', 'surface', 'surfaceAlt',
  'accent', 'link',
  'nav', 'navText',
  'textPrimary', 'textSecondary', 'textPlaceholder',
  'border', 'borderInput',
  'buttonBrandText', 'buttonNeutralBg',
  'tableHeaderBg',
  'modalBg', 'dropdownBg',
  'success', 'warning', 'error',
  'focusRing', 'scrollThumb',
];

/**
 * Derive a full theme colors object from core values.
 *
 * @param {Object} input - Object containing some or all of the 81 color keys.
 *   At minimum, the 23 core keys should be present.
 *   Any additional keys are treated as explicit overrides and won't be recalculated.
 * @returns {Object} Full colors object with all ~81 keys populated.
 */
function deriveFullTheme(input) {
  const c = { ...input };
  const isDark = c.colorScheme === 'dark';

  // Helper: set a key only if not already present (respects overrides)
  const derive = (key, valueFn) => {
    if (c[key] === undefined || c[key] === null) {
      c[key] = valueFn();
    }
  };

  // ── Surfaces ──────────────────────────────────────────────────────────────
  derive('surfaceHover',     () => isDark ? _lighten(c.surface, 5) : _darken(c.surface, 3));
  derive('surfaceHighlight', () => _alpha(c.accent, 0.10));
  derive('surfaceSelection', () => _alpha(c.accent, 0.15));

  // ── Accent variants ───────────────────────────────────────────────────────
  derive('accentHover',  () => _darken(c.accent, isDark ? 15 : 10));
  derive('accentActive', () => _darken(c.accent, isDark ? 25 : 20));
  derive('accentLight',  () => _alpha(c.accent, 0.15));

  // ── Text ──────────────────────────────────────────────────────────────────
  derive('textMuted', () => _mix(c.textSecondary, c.textPlaceholder, isDark ? 0.6 : 0.4));

  // ── Navigation ────────────────────────────────────────────────────────────
  derive('navHover',        () => 'rgba(255, 255, 255, 0.12)');
  derive('navActive',       () => 'rgba(255, 255, 255, 0.2)');
  // Most themes use navText for active border; accent-themed navs override in Advanced
  derive('navActiveBorder', () => c.navText);
  derive('navBorder',       () => _mix(c.nav, isDark ? '#000000' : '#000000', isDark ? 0.3 : 0.15));
  derive('navIcon',         () => c.navText);
  derive('navActiveText',   () => c.navText);
  derive('navAppName',      () => c.navText);
  derive('navAppBorder',    () => 'rgba(255, 255, 255, 0.2)');
  derive('navWaffleDot',    () => c.navText);

  // ── Links ─────────────────────────────────────────────────────────────────
  derive('linkHover', () => isDark ? _lighten(c.link, 12) : _darken(c.link, 20));

  // ── Borders ───────────────────────────────────────────────────────────────
  derive('borderSeparator', () => c.border);

  // ── Buttons ───────────────────────────────────────────────────────────────
  derive('buttonBrandBg',      () => c.accent);
  derive('buttonBrandBorder',  () => c.accent);
  derive('buttonBrandHover',   () => _darken(c.accent, 10));
  derive('buttonNeutralBorder', () => c.borderInput);
  derive('buttonNeutralHover',  () => isDark ? _lighten(c.surface, 5) : _darken(c.surface, 3));
  derive('buttonNeutralText',   () => c.textPrimary);

  // ── Tables ────────────────────────────────────────────────────────────────
  derive('tableHeaderText', () => c.textSecondary);
  derive('tableAltRow',     () => isDark ? _lighten(c.surface, 2) : _darken(c.surface, 1));
  derive('tableHoverRow',   () => _alpha(c.accent, 0.10));
  derive('tableBorderRow',  () => c.border);
  derive('tableColBorder',  () => isDark ? c.border : _lighten(c.border, 5));

  // ── Modals ────────────────────────────────────────────────────────────────
  derive('modalHeaderBg',  () => isDark ? _darken(c.surface, 5) : c.surface);
  derive('modalFooterBg',  () => isDark ? _darken(c.surface, 5) : c.background);
  derive('modalBackdrop',  () => isDark ? 'rgba(0, 0, 0, 0.65)' : 'rgba(0, 0, 0, 0.4)');
  derive('modalShadow',    () => isDark
    ? '0 20px 60px rgba(0, 0, 0, 0.6)'
    : '0 20px 60px rgba(0, 0, 0, 0.12)');

  // ── Dropdowns ─────────────────────────────────────────────────────────────
  derive('dropdownItemHoverBg',   () => _alpha(c.accent, 0.10));
  derive('dropdownItemHoverText', () => c.textPrimary);

  // ── Tabs ──────────────────────────────────────────────────────────────────
  derive('tabNavBorder',    () => c.border);
  derive('tabActiveColor',  () => c.accent);
  derive('tabActiveBorder', () => c.accent);
  derive('tabInactiveColor', () => c.textSecondary);
  derive('tabContentBg',    () => c.surface);

  // ── Focus ─────────────────────────────────────────────────────────────────
  // focusRing is a core key but if not set, derive it
  derive('focusRing', () => `0 0 0 3px ${_alpha(c.accent, 0.3)}`);

  // ── Scrollbar ─────────────────────────────────────────────────────────────
  derive('scrollTrack',     () => isDark ? _darken(c.background, 10) : _darken(c.background, 2));
  derive('scrollThumbHover', () => c.textPlaceholder);

  // ── Badges & Pills ────────────────────────────────────────────────────────
  derive('badgeBg',     () => isDark ? _alpha(c.accent, 0.15) : c.accent);
  derive('badgeText',   () => isDark ? c.accent : _contrast(c.accent));
  derive('badgeBorder', () => isDark ? `1px solid ${_alpha(c.accent, 0.3)}` : 'none');
  derive('pillBg',      () => _alpha(c.accent, 0.10));
  derive('pillBorder',  () => c.borderInput);
  derive('pillText',    () => c.textPrimary);

  // ── Panels ────────────────────────────────────────────────────────────────
  derive('panelBg',     () => c.surface);
  derive('panelBorder', () => c.border);

  // ── Search (primarily for dark themes with white header) ──────────────────
  derive('searchBg',          () => isDark ? _darken(c.surface, 10) : c.surface);
  derive('searchText',        () => isDark ? c.textPrimary : c.textPrimary);
  derive('searchBorder',      () => isDark ? c.border : c.borderInput);
  derive('searchPlaceholder', () => isDark ? c.textSecondary : c.textPlaceholder);
  derive('searchFocusBorder', () => c.accent);
  derive('searchFocusShadow', () => `0 0 0 2px ${_alpha(c.accent, 0.25)}`);

  // ── Global header ─────────────────────────────────────────────────────────
  derive('globalHeaderWhite', () => true);

  return c;
}

/**
 * Extract the 23 core values from a full theme colors object.
 * Useful for populating the editor from an existing theme.
 */
function extractCoreValues(fullColors) {
  const core = {};
  for (const key of CORE_KEYS) {
    if (fullColors[key] !== undefined) {
      core[key] = fullColors[key];
    }
  }
  return core;
}

/**
 * Resolve a custom theme: base theme + core overrides + derivation + advanced overrides.
 *
 * @param {Object} baseColors - Full colors from the base OOTB theme
 * @param {Object} coreOverrides - User's changes to core values (up to 23 keys)
 * @param {Object} advancedOverrides - User's changes to derived values
 * @returns {Object} Full resolved colors object
 */
function resolveCustomTheme(baseColors, coreOverrides, advancedOverrides) {
  // 1. Start with base theme's core values
  const core = extractCoreValues(baseColors);

  // 2. Apply user's core overrides
  Object.assign(core, coreOverrides || {});

  // 3. Run derivation engine (fills in ~58 derived values)
  const derived = deriveFullTheme(core);

  // 4. Apply user's advanced overrides (wins over derivation)
  Object.assign(derived, advancedOverrides || {});

  return derived;
}

// ─── Theme registry ──────────────────────────────────────────────────────────

// Loaded at startup from themes/themes.json.
// Kept in memory for the lifetime of the service worker.
let THEME_REGISTRY = { themes: [] };

async function loadThemeRegistry() {
  try {
    const url = chrome.runtime.getURL('themes/themes.json');
    const response = await fetch(url);
    if (!response.ok) throw new Error(`HTTP ${response.status}`);
    THEME_REGISTRY = await response.json();
  } catch (err) {
    console.error('[Salesforce Themer] Failed to load theme registry:', err);
  }
}

// ─── Theme sets for keyboard shortcuts ───────────────────────────────────────

function getLightThemeIds() {
  return THEME_REGISTRY.themes.filter(t => t.category === 'light').map(t => t.id);
}

function getDarkThemeIds() {
  return THEME_REGISTRY.themes.filter(t => t.category === 'dark').map(t => t.id);
}

function getAllThemeIds() {
  return THEME_REGISTRY.themes.map(t => t.id);
}

// ─── CSS generation + caching ─────────────────────────────────────────────────

async function cacheThemeCSS(themeId) {
  if (!themeId || themeId === 'none') return;

  // Check if it's a custom theme
  if (themeId.startsWith('custom-')) {
    return cacheCustomThemeCSS(themeId);
  }

  const theme = THEME_REGISTRY.themes.find(t => t.id === themeId);
  if (!theme) {
    console.warn('[Salesforce Themer] Unknown theme:', themeId);
    return;
  }
  try {
    const css = generateThemeCSS(theme);
    await chrome.storage.local.set({ [`themeCSS_${themeId}`]: css });
  } catch (err) {
    console.error('[Salesforce Themer] Failed to cache CSS for', themeId, err);
  }
}

async function cacheCustomThemeCSS(themeId) {
  try {
    const { customThemes } = await chrome.storage.sync.get('customThemes');
    if (!customThemes) return;

    const custom = customThemes.find(t => t.id === themeId);
    if (!custom) {
      console.warn('[Salesforce Themer] Unknown custom theme:', themeId);
      return;
    }

    // Find base theme
    const base = THEME_REGISTRY.themes.find(t => t.id === custom.basedOn);
    if (!base) {
      console.warn('[Salesforce Themer] Unknown base theme:', custom.basedOn);
      return;
    }

    // Resolve: base → core overrides → derivation → advanced overrides
    const resolvedColors = resolveCustomTheme(
      base.colors,
      custom.coreOverrides || {},
      custom.advancedOverrides || {}
    );

    const css = generateThemeCSS({ id: themeId, colors: resolvedColors });
    await chrome.storage.local.set({ [`themeCSS_${themeId}`]: css });
  } catch (err) {
    console.error('[Salesforce Themer] Failed to cache custom theme CSS:', themeId, err);
  }
}

async function cacheAllThemes() {
  // Cache OOTB themes
  for (const theme of THEME_REGISTRY.themes) {
    await cacheThemeCSS(theme.id);
  }

  // Cache custom themes
  try {
    const { customThemes } = await chrome.storage.sync.get('customThemes');
    if (customThemes && customThemes.length > 0) {
      for (const custom of customThemes) {
        await cacheCustomThemeCSS(custom.id);
      }
    }
  } catch (err) {
    console.error('[Salesforce Themer] Failed to cache custom themes:', err);
  }
}

// ─── Install / update handler ─────────────────────────────────────────────────

chrome.runtime.onInstalled.addListener(async (details) => {
  await loadThemeRegistry();

  if (details.reason === 'install') {
    await chrome.storage.sync.set({
      theme: 'connectry',
      autoMode: false,
      lastLightTheme: 'connectry',
      lastDarkTheme: 'connectry-dark',
      orgThemes: {},
      themeScope: 'both',
    });
  }

  await cacheAllThemes();
});

// Re-generate CSS when browser starts
chrome.runtime.onStartup.addListener(async () => {
  await loadThemeRegistry();
  await cacheAllThemes();
});

// Also regenerate on any service worker activation (covers extension refresh during dev)
(async () => {
  try {
    await loadThemeRegistry();
    await cacheAllThemes();
  } catch (_) {}
})();

// ─── Storage change handler ───────────────────────────────────────────────────

chrome.storage.onChanged.addListener(async (changes, area) => {
  if (area !== 'sync') return;
  if (changes.theme?.newValue) {
    // Ensure changed theme is cached (usually already is, but handles edge cases)
    if (!THEME_REGISTRY.themes.length) await loadThemeRegistry();
    await cacheThemeCSS(changes.theme.newValue);
  }
});

// ─── Keyboard commands ────────────────────────────────────────────────────────

chrome.commands.onCommand.addListener(async (command) => {
  if (!THEME_REGISTRY.themes.length) await loadThemeRegistry();

  const allIds = getAllThemeIds();
  const lightIds = new Set(getLightThemeIds());
  const darkIds = new Set(getDarkThemeIds());

  if (command === 'toggle-theme') {
    const result = await chrome.storage.sync.get({ theme: 'connectry', autoMode: false });
    if (result.autoMode) return;
    const idx = allIds.indexOf(result.theme);
    const next = allIds[(idx + 1) % allIds.length];
    await applyAndSaveTheme(next, lightIds, darkIds);
  }

  if (command === 'toggle-dark-light') {
    const result = await chrome.storage.sync.get({
      theme: 'connectry',
      lastLightTheme: 'connectry',
      lastDarkTheme: 'connectry-dark',
      autoMode: false,
    });
    if (result.autoMode) return;

    const next = darkIds.has(result.theme)
      ? result.lastLightTheme
      : result.lastDarkTheme;
    await applyAndSaveTheme(next, lightIds, darkIds);
  }
});

async function applyAndSaveTheme(themeId, lightIds, darkIds) {
  const updates = { theme: themeId };
  if (lightIds.has(themeId)) updates.lastLightTheme = themeId;
  else if (darkIds.has(themeId)) updates.lastDarkTheme = themeId;
  await chrome.storage.sync.set(updates);
  await cacheThemeCSS(themeId);
  await broadcastThemeToActiveTabs(themeId);
}

async function broadcastThemeToActiveTabs(themeId) {
  try {
    const tabs = await chrome.tabs.query({ active: true, currentWindow: true });
    for (const tab of tabs) {
      if (!tab.id) continue;
      chrome.tabs.sendMessage(tab.id, { action: 'setTheme', theme: themeId }).catch(() => {});
    }
  } catch (_) {}
}
