/**
 * Salesforce Themer — Theme Engine
 * Generates complete CSS from a theme color config.
 * Single source of truth for all selectors and CSS structure.
 */

'use strict';

function generateThemeCSS(theme) {
  const c = theme.colors;
  const isDark = c.colorScheme === 'dark';
  const fx = c.specialEffects || null;

  const accentRgb = hexToRgb(c.accent) || '74, 111, 165';

  return `
/* Auto-generated by Salesforce Themer engine — theme: ${theme.id} */

/* ─── CSS Custom Properties ─────────────────────────────────────────────── */

:root {
  color-scheme: ${c.colorScheme};

  /* Legacy LWC tokens */
  --lwc-colorBackground: ${c.background} !important;
  --lwc-colorBackgroundAlt: ${c.surface} !important;
  --lwc-colorBackgroundRow: ${c.surface} !important;
  --lwc-colorBackgroundRowHover: ${c.surfaceHover} !important;
  --lwc-colorBackgroundHighlight: ${c.surfaceHighlight} !important;
  --lwc-colorBackgroundSelection: ${c.surfaceSelection} !important;
  --lwc-colorBackgroundButtonBrand: ${c.buttonBrandBg} !important;
  --lwc-colorBackgroundButtonBrandHover: ${c.buttonBrandHover} !important;
  --lwc-colorBackgroundButtonBrandActive: ${c.accentActive} !important;
  --lwc-colorBackgroundButtonDefault: ${c.buttonNeutralBg} !important;
  --lwc-colorBackgroundButtonDefaultHover: ${c.buttonNeutralHover} !important;
  --lwc-headerColorBackground: ${c.nav} !important;
  --lwc-pageColorBackground: ${c.background} !important;
  --lwc-colorTextDefault: ${c.textPrimary} !important;
  --lwc-colorTextWeak: ${c.textSecondary} !important;
  --lwc-colorTextLabel: ${c.textSecondary} !important;
  --lwc-colorTextPlaceholder: ${c.textPlaceholder} !important;
  --lwc-colorTextButtonBrand: ${c.buttonBrandText} !important;
  --lwc-colorTextLink: ${c.link} !important;
  --lwc-colorTextLinkHover: ${c.linkHover} !important;
  --lwc-colorBorder: ${c.border} !important;
  --lwc-colorBorderSeparator: ${c.borderSeparator} !important;
  --lwc-colorBorderInput: ${c.borderInput} !important;
  --lwc-colorBorderInputActive: ${c.accent} !important;
  --lwc-brandPrimary: ${c.accent} !important;
  --lwc-brandPrimaryActive: ${c.accentHover} !important;
  --lwc-brandPrimaryTransparent: ${c.accentLight} !important;
  --lwc-brandAccessible: ${c.accent} !important;
  --lwc-brandAccessibleActive: ${c.accentHover} !important;
  --lwc-colorBackgroundSpin: ${c.accent} !important;
  --lwc-shadowOutlineFocus: ${c.focusRing} !important;

  /* SLDS 2 global tokens */
  --slds-g-color-surface-1: ${c.background} !important;
  --slds-g-color-surface-2: ${c.surface} !important;
  --slds-g-color-surface-3: ${c.surfaceHover} !important;
  --slds-g-color-surface-4: ${c.border} !important;
  --slds-g-color-on-surface-1: ${c.textPrimary} !important;
  --slds-g-color-on-surface-2: ${c.textSecondary} !important;
  --slds-g-color-on-surface-3: ${c.textMuted} !important;
  --slds-g-color-border-1: ${c.border} !important;
  --slds-g-color-border-2: ${c.borderInput} !important;
  --slds-g-color-brand-1: ${c.accent} !important;
  --slds-g-color-brand-2: ${c.accentHover} !important;
  --slds-g-color-brand-3: ${c.accentActive} !important;
  --slds-g-color-neutral-1: ${c.background} !important;
  --slds-g-color-neutral-2: ${c.surfaceAlt || c.surfaceHover} !important;
  --slds-g-color-neutral-3: ${c.border} !important;

  /* Component hooks */
  --slds-c-card-color-background: ${c.surface} !important;
  --slds-c-card-color-border: ${c.border} !important;
  --slds-c-input-color-background: ${isDark ? c.background : c.surface} !important;
  --slds-c-input-color-border: ${c.borderInput} !important;
  --slds-c-input-color-border-focus: ${c.accent} !important;
  --slds-c-button-brand-color-background: ${c.buttonBrandBg} !important;
  --slds-c-button-brand-color-border: ${c.buttonBrandBorder} !important;
  --slds-c-button-brand-color-background-hover: ${c.buttonBrandHover} !important;
  --slds-c-button-neutral-color-background: ${c.buttonNeutralBg} !important;
  --slds-c-button-neutral-color-border: ${c.buttonNeutralBorder} !important;
}

/* ─── Base ───────────────────────────────────────────────────────────────── */

html,
body,
.desktop {
  background-color: ${c.background} !important;
  color: ${c.textPrimary} !important;${fx && fx.gridOverlay ? `
  background-image:
    repeating-linear-gradient(
      0deg,
      transparent,
      transparent 39px,
      rgba(${hexToRgb(c.accent)}, 0.02) 39px,
      rgba(${hexToRgb(c.accent)}, 0.02) 40px
    ),
    repeating-linear-gradient(
      90deg,
      transparent,
      transparent 39px,
      rgba(${hexToRgb(c.accent)}, 0.02) 39px,
      rgba(${hexToRgb(c.accent)}, 0.02) 40px
    ) !important;
  background-attachment: fixed !important;` : ''}
}

/* ─── Global Header — always white so SF logo/icons remain visible ────── */
${c.globalHeaderWhite ? `
.slds-global-header,
.slds-global-header_container,
.forceSearchDesktopHeader {
  background-color: #ffffff !important;
  color: #2d2d2d !important;
}` : ''}

${isDark || !c.globalHeaderWhite ? `
/* Search box in header — themed for dark or non-white-header themes */
.slds-global-header .slds-input,
.slds-global-header input[type="search"],
.forceSearchDesktopHeader input,
.slds-global-header .slds-form-element__control input {
  background-color: ${c.searchBg || c.surface} !important;
  color: ${c.searchText || c.textPrimary} !important;
  border-color: ${c.searchBorder || c.border} !important;
  border-radius: 6px !important;${fx && fx.glowOnHover ? `
  box-shadow: 0 0 6px ${c.accentLight} !important;` : ''}
}

.slds-global-header .slds-input::placeholder,
.slds-global-header input::placeholder {
  color: ${c.searchPlaceholder || c.textPlaceholder} !important;
}

.slds-global-header .slds-input:focus,
.slds-global-header input:focus {
  border-color: ${c.searchFocusBorder || c.accent} !important;
  box-shadow: ${c.searchFocusShadow || c.focusRing} !important;
}` : ''}

/* ─── Navigation ─────────────────────────────────────────────────────────── */

.oneGlobalNav,
one-app-nav-bar,
.navexConsoleTabBar,
[class*="globalNavigation"],
.slds-context-bar {
  background-color: ${c.nav} !important;
  border-bottom: 1px solid ${c.navBorder} !important;${fx && fx.navBoxShadow ? `
  box-shadow: ${fx.navBoxShadow} !important;` : ''}
}

.slds-context-bar__item,
.navexConsoleTabItem,
.oneConsoleTabItem {
  color: ${c.navText} !important;
}

.slds-context-bar__item:hover,
.navexConsoleTabItem:hover {
  background-color: ${c.navHover} !important;${c.navActiveText !== c.navText ? `
  color: ${c.navActiveText} !important;` : ''}
}

.slds-context-bar__item.slds-is-active,
.navexConsoleTabItem.active {
  background-color: ${c.navActive} !important;
  border-bottom: 3px solid ${c.navActiveBorder} !important;${fx && fx.navActiveBoxShadow ? `
  box-shadow: ${fx.navActiveBoxShadow} !important;` : ''}
  color: ${c.navActiveText} !important;
}

/* Active tab link text */
.slds-context-bar__item.slds-is-active .slds-context-bar__label-action,
.slds-context-bar__item.slds-is-active a {
  color: ${c.navActiveText} !important;
  background-color: transparent !important;
}

/* Nav text and icons */
.slds-context-bar__label-action,
.slds-context-bar__icon-action,
.slds-context-bar .slds-icon {
  color: ${c.navIcon} !important;
  fill: ${c.navIcon} !important;
}

/* App launcher button */
.slds-context-bar__app-name,
.appLauncherButton {
  color: ${c.navAppName} !important;
  border-right: 1px solid ${c.navAppBorder} !important;${fx ? `
  text-shadow: 0 0 8px ${c.accentLight} !important;` : ''}
}

/* App launcher waffle dots — target individual dots, not the container */
.slds-icon-waffle .slds-r1,
.slds-icon-waffle .slds-r2,
.slds-icon-waffle .slds-r3,
.slds-icon-waffle .slds-r4,
.slds-icon-waffle .slds-r5,
.slds-icon-waffle .slds-r6,
.slds-icon-waffle .slds-r7,
.slds-icon-waffle .slds-r8,
.slds-icon-waffle .slds-r9 {
  background-color: ${c.navWaffleDot} !important;
}

/* ─── Main Content ───────────────────────────────────────────────────────── */

.oneContent,
.oneWorkspace,
.flexipageBody,
.onesetupSetupLayout,
.setupcontent {
  background-color: ${fx && fx.gridOverlay ? 'transparent' : c.background} !important;
}

/* ─── Page Headers ───────────────────────────────────────────────────────── */

.slds-page-header,
.forceListViewManager .listViewManager,
[class*="pageHeader"] {
  background-color: ${c.surface} !important;
  border-bottom: 1px solid ${c.border} !important;
  box-shadow: ${isDark ? '0 1px 0 rgba(255, 255, 255, 0.04)' : '0 1px 3px rgba(0, 0, 0, 0.06)'} !important;${fx ? `
  box-shadow: 0 1px 20px rgba(${hexToRgb(c.accent)}, 0.06) !important;` : ''}
}

.slds-page-header__title,
.slds-page-header__name-title {
  color: ${c.textPrimary} !important;${fx ? `
  text-shadow: 0 0 12px rgba(${hexToRgb(c.accent)}, 0.3) !important;` : ''}
}

.slds-page-header__meta-text {
  color: ${c.textSecondary} !important;
}

/* ─── Cards ──────────────────────────────────────────────────────────────── */

.slds-card,
.slds-card__body,
.slds-card__footer,
.forceRecordCard {
  background-color: ${c.surface} !important;
  border-color: ${c.border} !important;
  box-shadow: ${isDark ? '0 1px 4px rgba(0, 0, 0, 0.2)' : '0 1px 4px rgba(0, 0, 0, 0.06)'} !important;${isDark ? `
  color: ${c.textPrimary} !important;` : ''}${fx ? `
  box-shadow: 0 0 20px rgba(${hexToRgb(c.accent)}, 0.06), inset 0 0 40px rgba(0, 0, 0, 0.2) !important;` : ''}
}
${fx ? `
.slds-card:hover {
  border-color: ${fx.cardHoverBorder} !important;
  box-shadow: ${fx.cardHoverShadow} !important;
}` : ''}

.slds-card__header {
  background-color: ${c.surface} !important;
  border-color: ${c.border} !important;
  border-bottom: 1px solid ${isDark ? 'rgba(255,255,255,0.06)' : c.border} !important;
}

/* ─── Buttons ────────────────────────────────────────────────────────────── */

.slds-button_brand,
.slds-button--brand {
  background-color: ${c.buttonBrandBg} !important;
  border: 1px solid ${c.buttonBrandBorder} !important;
  color: ${c.buttonBrandText} !important;${fx ? `
  text-shadow: 0 0 8px rgba(${hexToRgb(c.accent)}, 0.5) !important;
  box-shadow: 0 0 10px rgba(${hexToRgb(c.accent)}, 0.15), inset 0 0 10px rgba(${hexToRgb(c.accent)}, 0.05) !important;` : ''}
}

.slds-button_brand:hover,
.slds-button--brand:hover {
  background-color: ${c.buttonBrandHover} !important;
  border-color: ${c.buttonBrandHover} !important;${fx ? `
  box-shadow: 0 0 20px rgba(${hexToRgb(c.accent)}, 0.3), inset 0 0 20px rgba(${hexToRgb(c.accent)}, 0.1) !important;` : ''}
}

.slds-button_neutral,
.slds-button--neutral {
  background-color: ${c.buttonNeutralBg} !important;
  border-color: ${c.buttonNeutralBorder} !important;
  color: ${c.buttonNeutralText} !important;
}

.slds-button_neutral:hover,
.slds-button--neutral:hover {
  background-color: ${c.buttonNeutralHover} !important;
}

/* ─── Form Elements ──────────────────────────────────────────────────────── */

.slds-input,
.slds-textarea,
.slds-select,
.slds-combobox__form-element,
.slds-has-input-focus .slds-input {
  background-color: ${isDark ? c.background : c.surface} !important;
  border-color: ${c.borderInput} !important;
  color: ${c.textPrimary} !important;
}

.slds-input:focus,
.slds-textarea:focus,
.slds-select:focus {
  border-color: ${c.accent} !important;
  box-shadow: ${isDark
    ? `0 0 0 3px rgba(${hexToRgb(c.accent)}, 0.2)${fx ? `, 0 0 12px rgba(${hexToRgb(c.accent)}, 0.15)` : ''}`
    : `0 0 0 3px rgba(${hexToRgb(c.accent)}, 0.2)`
  } !important;
  outline: none !important;
}

.slds-input::placeholder,
.slds-textarea::placeholder {
  color: ${c.textPlaceholder} !important;
}

.slds-form-element__label {
  color: ${c.textSecondary} !important;
  font-weight: 500 !important;
}

/* ─── Tables ─────────────────────────────────────────────────────────────── */

.slds-table {
  background-color: ${c.surface} !important;
  border: 1px solid ${c.border} !important;
}

.slds-table thead th,
.slds-table thead td {
  background-color: ${c.tableHeaderBg} !important;
  color: ${c.tableHeaderText} !important;
  border-bottom: ${isDark ? '2px' : '2px'} solid ${c.border} !important;
  font-weight: 600 !important;${fx ? `
  text-transform: uppercase !important;
  font-size: 11px !important;
  letter-spacing: 0.08em !important;
  text-shadow: 0 0 8px rgba(${hexToRgb(c.accent)}, 0.4) !important;` : ''}
}

.slds-table tbody tr {
  background-color: ${c.surface} !important;
  border-bottom: 1px solid ${c.tableBorderRow} !important;
  color: ${c.textPrimary} !important;
}

.slds-table tbody tr:nth-child(even) {
  background-color: ${c.tableAltRow} !important;
}

.slds-table tbody tr:hover {
  background-color: ${c.tableHoverRow} !important;${fx ? `
  box-shadow: inset 0 0 20px rgba(${hexToRgb(c.accent)}, 0.04) !important;` : ''}
}

.slds-table td,
.slds-table th {
  color: ${c.textPrimary} !important;
  border-right: 1px solid ${c.tableColBorder} !important;
}

/* ─── Modals ─────────────────────────────────────────────────────────────── */

.slds-modal__container {
  background-color: ${c.modalBg} !important;
  border: 1px solid ${c.border} !important;
  box-shadow: ${c.modalShadow} !important;
}

.slds-modal__header {
  background-color: ${c.modalHeaderBg} !important;
  border-bottom: 1px solid ${c.border} !important;
  color: ${c.textPrimary} !important;
}

.slds-modal__content {
  background-color: ${c.modalBg} !important;
  color: ${c.textPrimary} !important;
}

.slds-modal__footer {
  background-color: ${c.modalFooterBg} !important;
  border-top: 1px solid ${c.border} !important;
}

.slds-backdrop {
  background-color: ${c.modalBackdrop} !important;${fx ? `
  backdrop-filter: blur(2px) !important;` : ''}
}

/* ─── Dropdowns & Popovers ───────────────────────────────────────────────── */

.slds-dropdown,
.slds-dropdown__list {
  background-color: ${c.dropdownBg} !important;
  border: 1px solid ${c.border} !important;
  box-shadow: ${isDark ? '0 8px 24px rgba(0, 0, 0, 0.5)' : '0 4px 16px rgba(0, 0, 0, 0.10)'} !important;${fx ? `
  box-shadow: 0 0 30px rgba(${hexToRgb(c.accent)}, 0.12), 0 8px 24px rgba(0, 0, 0, 0.6) !important;` : ''}
}

.slds-dropdown__item > a,
.slds-dropdown__item > span {
  color: ${c.textPrimary} !important;
}

.slds-dropdown__item:hover > a,
.slds-dropdown__item:hover > span,
.slds-dropdown__item:focus > a {
  background-color: ${c.dropdownItemHoverBg} !important;
  color: ${c.dropdownItemHoverText} !important;
}

.slds-popover {
  background-color: ${c.dropdownBg} !important;
  border: 1px solid ${c.border} !important;
  box-shadow: ${isDark ? '0 8px 24px rgba(0, 0, 0, 0.45)' : '0 4px 16px rgba(0, 0, 0, 0.10)'} !important;
  color: ${c.textPrimary} !important;
}

/* ─── Tabs ───────────────────────────────────────────────────────────────── */

.slds-tabs_default__nav,
.slds-tabs--default__nav {
  border-bottom: 2px solid ${c.tabNavBorder} !important;
  background-color: transparent !important;
}

.slds-tabs_default__item,
.slds-tabs--default__item {
  color: ${c.tabInactiveColor} !important;
}

.slds-tabs_default__item.slds-is-active,
.slds-tabs--default__item.slds-active {
  color: ${c.tabActiveColor} !important;
  border-bottom: 2px solid ${c.tabActiveBorder} !important;${fx ? `
  text-shadow: 0 0 10px rgba(${hexToRgb(c.accent)}, 0.5) !important;` : ''}
}

.slds-tabs_default__content,
.slds-tabs--default__content {
  background-color: ${c.tabContentBg} !important;
}

/* ─── Pills & Badges ─────────────────────────────────────────────────────── */

.slds-pill {
  background-color: ${c.pillBg} !important;
  border: 1px solid ${c.pillBorder} !important;
  color: ${c.pillText} !important;
}

.slds-badge {
  background-color: ${c.badgeBg} !important;
  color: ${c.badgeText} !important;${c.badgeBorder !== 'none' ? `
  border: ${c.badgeBorder} !important;` : ''}${fx ? `
  text-shadow: 0 0 6px rgba(${hexToRgb(c.accent)}, 0.5) !important;` : ''}
}

/* ─── Scrollbars ─────────────────────────────────────────────────────────── */

::-webkit-scrollbar {
  width: ${fx ? '6px' : '8px'} !important;
  height: ${fx ? '6px' : '8px'} !important;
}

::-webkit-scrollbar-track {
  background: ${c.scrollTrack} !important;${fx ? `
  border-left: 1px solid rgba(${hexToRgb(c.accent)}, 0.06) !important;` : ''}
}

::-webkit-scrollbar-thumb {
  background: ${c.scrollThumb} !important;
  border-radius: ${fx ? '3px' : '4px'} !important;
}

::-webkit-scrollbar-thumb:hover {
  background: ${c.scrollThumbHover} !important;${fx && fx.glowOnHover ? `
  box-shadow: 0 0 6px rgba(${hexToRgb(c.accent)}, 0.3) !important;` : ''}
}

/* ─── Record Detail ──────────────────────────────────────────────────────── */

.forceOutputField,
.slds-form-element__static {
  color: ${c.textPrimary} !important;
}

/* ─── Sidebar / Panel ────────────────────────────────────────────────────── */

.slds-panel,
.slds-split-view_container {
  background-color: ${c.panelBg} !important;
  border-right: 1px solid ${c.panelBorder} !important;
}

/* ─── Links ──────────────────────────────────────────────────────────────── */

a,
.slds-truncate a,
.forceOutputLookup a {
  color: ${c.link} !important;${fx && fx.linkTextShadow ? `
  text-shadow: ${fx.linkTextShadow} !important;` : ''}
}

a:hover {
  color: ${c.linkHover} !important;${fx && fx.linkHoverTextShadow ? `
  text-shadow: ${fx.linkHoverTextShadow} !important;` : ''}
}

/* ─── Setup Pages ────────────────────────────────────────────────────────── */

.setupcontent,
.slds-setup-assistant,
.setup-page,
[class*="setupLayout"],
.onesetupSetupLayout,
.setupTabContent,
.slds-setup-summary,
.forceSetupDesktop {
  background-color: ${c.background} !important;
  color: ${c.textPrimary} !important;
}

/* ─── Reports ────────────────────────────────────────────────────────────── */

.report-container,
.reportOutput,
[class*="reportPage"],
.slds-report,
.forceReportOutput,
.reportHeader {
  background-color: ${c.background} !important;
  color: ${c.textPrimary} !important;
}

/* ─── Console / Service Console ──────────────────────────────────────────── */

.navexConsoleContent,
.workspaceManager,
.split-view,
.slds-split-view,
[class*="console"] {
  background-color: ${c.background} !important;
  color: ${c.textPrimary} !important;
}

/* ─── Record Page Header / Highlights ────────────────────────────────────── */

.highlights,
.forceHighlightsStencilDesktop,
.forceRecordLayout,
.forceHighlightsPanel,
.slds-page-header--record-home,
.slds-page-header_record-home,
.flexipageHeader,
.record-page-decorator,
.recordHomeTemplate,
.forceHighlightsLayout {
  background-color: ${c.background} !important;
  color: ${c.textPrimary} !important;
  border-color: ${c.border} !important;
  box-shadow: ${isDark ? '0 1px 3px rgba(0, 0, 0, 0.15)' : '0 1px 3px rgba(0, 0, 0, 0.06)'} !important;
}

/* Record page full body background */
.flexipagePage,
.flexipage-template,
.uiTabBar + .tabContent,
.forceRecordFlexiPage {
  background-color: ${c.background} !important;
}

/* ─── Path / Stage Path ─────────────────────────────────────────────────── */

/* Path structural containers — recolor, keep structure */
.slds-path,
.slds-path__scroller,
.slds-path__track,
.slds-path__wrap,
.slds-path__coach,
.slds-path__nav,
.slds-path__scroller-container,
.slds-path__scroller_inner,
.slds-path__scroll-controls,
.slds-grid.slds-path__track,
.pathAssistantContainer,
.forcePathAssistant,
lightning-sales-path,
records-lwc-highlights-panel,
.runtime_sales_pathassistantPathAssistantTabSet,
.runtime_sales_pathassistantPathAssistantHeader,
.uiScroller.slds-path__scroller,
[class*="pathAssistant"],
[class*="PathAssistant"],
[class*="salesPath"],
[class*="SalesPath"] {
  background-color: ${c.surface} !important;
  color: ${c.textPrimary} !important;
}

/* Path scroller inner wrapper */
.slds-path__scroller .scroller,
.slds-path__scroller .slds-path__scroller_inner {
  background-color: ${c.surface} !important;
}

/* The slds-card wrapping the path — recolor, keep structure */
body .pathOriginal .slds-card,
body .pathOriginal .slds-card__body,
body .pathOriginal .slds-card__body_inner,
body .runtime_sales_pathassistantPathAssistant .slds-card,
body .runtime_sales_pathassistantPathAssistant .slds-card__body,
body .runtime_sales_pathassistantPathAssistant .slds-card__body_inner,
body .runtime_sales_pathassistantPathAssistant > article,
body .forcePathAssistant .slds-card,
body .forcePathAssistant .slds-card__body,
body .forcePathAssistant .slds-card__body_inner {
  background-color: ${c.surface} !important;
  border-color: ${c.border} !important;
  box-shadow: ${isDark ? '0 1px 4px rgba(0, 0, 0, 0.2)' : '0 1px 4px rgba(0, 0, 0, 0.06)'} !important;
}

/* Path items — boosted specificity with body prefix */
body .slds-path__item,
body .slds-path__item .slds-path__link,
body .slds-path__item a.slds-path__link {
  background-color: ${c.surfaceAlt} !important;
}

body .slds-path__item.slds-is-complete,
body .slds-path__item.slds-is-complete .slds-path__link,
body .slds-path__item.slds-is-complete a.slds-path__link {
  background-color: ${c.accent} !important;
}

body .slds-path__item.slds-is-current,
body .slds-path__item.slds-is-current .slds-path__link,
body .slds-path__item.slds-is-current a.slds-path__link {
  background-color: ${c.accent} !important;
}

body .slds-path__item.slds-is-incomplete,
body .slds-path__item.slds-is-incomplete .slds-path__link,
body .slds-path__item.slds-is-incomplete a.slds-path__link {
  background-color: ${c.surfaceAlt} !important;
}

/* Path chevrons — SLDS uses skewed ::before/::after with background, NOT border triangles */
/* Each state must set background on BOTH the item AND its pseudo-elements */

/* Incomplete (default) — item + pseudo-elements */
body .slds-path__item::before,
body .slds-path__item::after {
  background: ${c.surfaceAlt} !important;
}

body .slds-path__item.slds-is-incomplete::before,
body .slds-path__item.slds-is-incomplete::after {
  background: ${c.surfaceAlt} !important;
}

/* Complete */
body .slds-path__item.slds-is-complete::before,
body .slds-path__item.slds-is-complete::after {
  background: ${c.accent} !important;
}

/* Current */
body .slds-path__item.slds-is-current::before,
body .slds-path__item.slds-is-current::after {
  background-color: ${c.accent} !important;
  background-image: none !important;
}

/* Active / selected */
body .slds-path__item.slds-is-active,
body .slds-path__item.slds-is-active .slds-path__link,
body .slds-path__item[aria-selected="true"],
body .slds-path__item [aria-selected="true"] {
  background-color: ${c.accent} !important;
  color: ${c.buttonBrandText} !important;
}

body .slds-path__item.slds-is-active::before,
body .slds-path__item.slds-is-active::after {
  background: ${c.accent} !important;
}

/* Hover — incomplete items */
.slds-path__item:hover,
.slds-path__item:hover .slds-path__link {
  background-color: ${c.surfaceHover} !important;
}

.slds-path__item:hover::before,
.slds-path__item:hover::after {
  background: ${c.surfaceHover} !important;
}

/* Hover — complete/current items */
.slds-path__item.slds-is-complete:hover,
.slds-path__item.slds-is-complete:hover .slds-path__link,
.slds-path__item.slds-is-current:hover,
.slds-path__item.slds-is-current:hover .slds-path__link {
  background-color: ${c.accentHover} !important;
}

.slds-path__item.slds-is-complete:hover::before,
.slds-path__item.slds-is-complete:hover::after,
.slds-path__item.slds-is-current:hover::before,
.slds-path__item.slds-is-current:hover::after {
  background: ${c.accentHover} !important;
}

/* Path text colors */
.slds-path__title {
  color: ${c.textPrimary} !important;
}

.slds-path__item.slds-is-complete .slds-path__title,
.slds-path__item.slds-is-current .slds-path__title {
  color: ${c.buttonBrandText} !important;
}

/* Path stage icon (checkmark on completed) */
.slds-path__stage {
  color: ${c.buttonBrandText} !important;
}

/* ─── Related List Cards (right sidebar) ─────────────────────────────────── */

/* Related list containers — background only, cards handle their own borders */
.forceRelatedListContainer,
.forceRelatedListSingleContainer {
  background-color: ${c.background} !important;
}

/* ─── Profile Icon / Global Actions (top right) ─────────────────────────── */

.slds-global-actions,
.slds-global-actions__item,
.slds-global-actions__item > *,
.forceUserProfileMenu,
.profileTrigger,
.oneUserProfileCardTrigger,
.slds-global-header__item--button,
.slds-global-actions__favorites,
.slds-global-actions__setup,
.slds-global-actions__help,
.slds-global-actions__notifications {
  background-color: transparent !important;
  border: none !important;
  box-shadow: none !important;
}

/* Profile avatar container specifically */
.slds-avatar,
.forceSocialPhoto,
.uiImage[class*="profilePhoto"],
.photoContainer {
  background-color: transparent !important;
  border: none !important;
  box-shadow: none !important;
}
`;
}

/**
 * Convert hex color to "R, G, B" string for use in rgba().
 * Returns a fallback string if parsing fails.
 * @param {string} hex
 * @returns {string}
 */
function hexToRgb(hex) {
  if (!hex || typeof hex !== 'string') return '74, 111, 165';
  // Strip leading # and handle short hex
  const clean = hex.replace('#', '');
  if (clean.length === 3) {
    const r = parseInt(clean[0] + clean[0], 16);
    const g = parseInt(clean[1] + clean[1], 16);
    const b = parseInt(clean[2] + clean[2], 16);
    return `${r}, ${g}, ${b}`;
  }
  if (clean.length === 6) {
    const r = parseInt(clean.slice(0, 2), 16);
    const g = parseInt(clean.slice(2, 4), 16);
    const b = parseInt(clean.slice(4, 6), 16);
    return `${r}, ${g}, ${b}`;
  }
  return '74, 111, 165';
}

// Export for use in background.js (service worker context — no ES modules)
if (typeof module !== 'undefined') {
  module.exports = { generateThemeCSS, hexToRgb };
}
