/**
 * Salesforce Themer — Theme Engine
 * Generates complete CSS from a theme color config.
 * Single source of truth for all selectors and CSS structure.
 */

'use strict';

// Font stack lookup — must match the FONT_STACKS in options.js
const _FONT_STACKS = {
  'system-ui':      'system-ui, sans-serif',
  'neo-grotesque':  "Inter, Roboto, 'Helvetica Neue', 'Arial Nova', 'Nimbus Sans', Arial, sans-serif",
  'humanist':       "Seravek, 'Gill Sans Nova', Ubuntu, Calibri, 'DejaVu Sans', source-sans-pro, sans-serif",
  'geometric':      "Avenir, Montserrat, Corbel, 'URW Gothic', source-sans-pro, sans-serif",
  'classic-serif':  "Charter, 'Bitstream Charter', 'Sitka Text', Cambria, serif",
};

function _generateTypographyCSS(typo) {
  if (!typo) return '';
  const bodyStack = _FONT_STACKS[typo.fontFamily] || _FONT_STACKS['system-ui'];
  const headingStack = typo.fontFamilyHeading ? (_FONT_STACKS[typo.fontFamilyHeading] || bodyStack) : null;
  const scale = typo.sizeScale || 1.0;
  const isDefault = typo.fontFamily === 'system-ui' && scale === 1.0
    && typo.weightBody === 400 && typo.weightHeading === 700
    && typo.lineHeight === 1.375 && !typo.letterSpacing
    && !typo.fontFamilyHeading;
  if (isDefault) return '';

  // SLDS 1 font sizes (rem values from Salesforce's token set)
  const sizes = {
    XSmall: 0.625, Small: 0.875, Medium: 1, Large: 1.125, XLarge: 1.25, XxLarge: 2,
  };

  let css = '\n/* ─── Typography overrides ──────────────────────────────────────────── */\n\n:root {\n';
  css += `  --lwc-fontFamily: ${bodyStack} !important;\n`;
  if (headingStack) css += `  --lwc-fontFamilyHeading: ${headingStack} !important;\n`;
  css += `  --slds-g-font-family: ${bodyStack} !important;\n`;

  // Weight tokens
  if (typo.weightBody !== 400) {
    css += `  --lwc-fontWeightRegular: ${typo.weightBody} !important;\n`;
    css += `  --slds-g-font-weight-4: ${typo.weightBody} !important;\n`;
  }
  if (typo.weightHeading !== 700) {
    css += `  --lwc-fontWeightBold: ${typo.weightHeading} !important;\n`;
    css += `  --slds-g-font-weight-7: ${typo.weightHeading} !important;\n`;
  }

  // Line height
  if (typo.lineHeight !== 1.375) {
    css += `  --lwc-lineHeightText: ${typo.lineHeight} !important;\n`;
    css += `  --lwc-lineHeightHeading: ${Math.max(1.1, typo.lineHeight - 0.125)} !important;\n`;
  }

  // Size scaling — multiply each SLDS 1 fontSize token
  if (scale !== 1.0) {
    for (const [suffix, rem] of Object.entries(sizes)) {
      const scaled = (rem * scale).toFixed(4).replace(/0+$/, '').replace(/\.$/, '');
      css += `  --lwc-fontSize${suffix}: ${scaled}rem !important;\n`;
    }
    css += `  --slds-g-font-size-base: ${(1 * scale).toFixed(3).replace(/0+$/, '').replace(/\.$/, '')}rem !important;\n`;
  }

  css += '}\n';

  // Font-family fallback on body (some elements don't inherit from tokens)
  css += `\nbody, .desktop, .oneContent, .slds-scope {\n  font-family: ${bodyStack} !important;\n`;
  if (typo.letterSpacing) css += `  letter-spacing: ${typo.letterSpacing}em !important;\n`;
  css += '}\n';

  // Heading font-family override if different from body
  if (headingStack) {
    css += `\n.slds-text-heading_large, .slds-text-heading_medium, .slds-text-heading_small,\n.slds-page-header__title, h1, h2, h3 {\n  font-family: ${headingStack} !important;\n}\n`;
  }

  // SLDS utility class size overrides (safety net — these use hardcoded values, not tokens)
  if (scale !== 1.0) {
    css += `\n.slds-text-heading_large { font-size: ${(1.5 * scale).toFixed(3)}rem !important; }\n`;
    css += `.slds-text-heading_medium { font-size: ${(1.25 * scale).toFixed(3)}rem !important; }\n`;
    css += `.slds-text-heading_small { font-size: ${(0.875 * scale).toFixed(3)}rem !important; }\n`;
    css += `.slds-text-body_regular { font-size: ${(0.875 * scale).toFixed(3)}rem !important; }\n`;
    css += `.slds-text-body_small { font-size: ${(0.75 * scale).toFixed(3)}rem !important; }\n`;
  }

  return css;
}

function generateThemeCSS(theme) {
  const c = theme.colors;
  const isDark = c.colorScheme === 'dark';
  const fx = c.specialEffects || null;
  const typo = theme.typography || null;

  const accentRgb = hexToRgb(c.accent) || '74, 111, 165';

  const brandBright = c.brandBright || c.accent;
  const iconColor = c.iconColor || c.textSecondary;
  const onSurface1 = c.onSurface1 || c.textPrimary;
  const onSurface2 = c.onSurface2 || c.textSecondary;
  const onSurface3 = c.onSurface3 || c.textMuted;
  const borderStrong = c.borderStrong || c.borderInput;
  const buttonBrandDisabledBg = c.buttonBrandDisabledBg || c.textMuted;
  const buttonBrandDisabledText = c.buttonBrandDisabledText || c.textMuted;
  const buttonNeutralBorderDefault = c.buttonNeutralBorderDefault || c.buttonBrandBorder;
  const buttonNeutralText = c.buttonNeutralText || c.textPrimary;
  const inputSearchBg = c.inputSearchBg || (isDark ? c.background : c.surface);

  return `
/* Auto-generated by Salesforce Themer engine — theme: ${theme.id} */

/* ─── CSS Custom Properties ─────────────────────────────────────────────── */

:root {
  color-scheme: ${c.colorScheme};

  /* Legacy LWC tokens */
  --lwc-colorBackground: ${c.background} !important;
  --lwc-colorBackgroundAlt: ${c.surface} !important;
  --lwc-colorBackgroundRow: ${c.surface} !important;
  --lwc-colorBackgroundRowHover: ${c.surfaceHover} !important;
  --lwc-colorBackgroundHighlight: ${c.surfaceHighlight} !important;
  --lwc-colorBackgroundSelection: ${c.surfaceSelection} !important;
  --lwc-colorBackgroundButtonBrand: ${c.buttonBrandBg} !important;
  --lwc-colorBackgroundButtonBrandHover: ${c.buttonBrandHover} !important;
  --lwc-colorBackgroundButtonBrandActive: ${c.accentActive} !important;
  --lwc-colorBackgroundButtonDefault: ${c.buttonNeutralBg} !important;
  --lwc-colorBackgroundButtonDefaultHover: ${c.buttonNeutralHover} !important;
  --lwc-headerColorBackground: ${c.nav} !important;
  --lwc-pageColorBackground: ${c.background} !important;
  --lwc-colorTextDefault: ${c.textPrimary} !important;
  --lwc-colorTextWeak: ${c.textSecondary} !important;
  --lwc-colorTextLabel: ${c.textSecondary} !important;
  --lwc-colorTextPlaceholder: ${c.textPlaceholder} !important;
  --lwc-colorTextButtonBrand: ${c.buttonBrandText} !important;
  --lwc-colorTextLink: ${c.link} !important;
  --lwc-colorTextLinkHover: ${c.linkHover} !important;
  --lwc-colorBorder: ${c.border} !important;
  --lwc-colorBorderSeparator: ${c.borderSeparator} !important;
  --lwc-colorBorderInput: ${c.borderInput} !important;
  --lwc-colorBorderInputActive: ${brandBright} !important;
  --lwc-brandPrimary: ${c.accent} !important;
  --lwc-brandPrimaryActive: ${c.accentHover} !important;
  --lwc-brandPrimaryTransparent: ${c.accentLight} !important;
  --lwc-brandAccessible: ${c.accent} !important;
  --lwc-brandAccessibleActive: ${c.accentHover} !important;
  --lwc-colorBackgroundSpin: ${c.accent} !important;
  --lwc-shadowOutlineFocus: ${c.focusRing} !important;

  /* SLDS 2 global tokens */
  --slds-g-color-surface-1: ${c.surface} !important;
  --slds-g-color-surface-2: ${c.background} !important;
  --slds-g-color-surface-3: ${c.surfaceHover} !important;
  --slds-g-color-surface-4: ${c.border} !important;
  --slds-g-color-on-surface-1: ${onSurface1} !important;
  --slds-g-color-on-surface-2: ${onSurface2} !important;
  --slds-g-color-on-surface-3: ${onSurface3} !important;
  --slds-g-color-border-1: ${c.borderInput} !important;
  --slds-g-color-border-2: ${borderStrong} !important;
  --slds-g-color-brand-1: ${c.accent} !important;
  --slds-g-color-brand-2: ${c.accentHover} !important;
  --slds-g-color-brand-3: ${c.accentActive} !important;
  --slds-g-color-neutral-1: ${c.background} !important;
  --slds-g-color-neutral-2: ${c.surfaceAlt || c.surfaceHover} !important;
  --slds-g-color-neutral-3: ${c.border} !important;

  /* SLDS 2 surface containers */
  --slds-g-color-surface-container-1: ${c.surface} !important;
  --slds-g-color-surface-container-2: ${c.surfaceHover} !important;
  --slds-g-color-surface-container-3: ${c.border} !important;

  /* SLDS 2 accent */
  --slds-g-color-accent-1: ${c.accent} !important;
  --slds-g-color-accent-2: ${c.accentHover} !important;
  --slds-g-color-accent-3: ${c.accentLight} !important;

  /* Legacy LWC — brand */
  --lwc-colorBrand: ${brandBright} !important;
  --lwc-colorBrandDark: ${c.accent} !important;
  --lwc-colorBrandDarker: ${c.accentActive} !important;
  --lwc-colorTextBrand: ${brandBright} !important;
  --lwc-colorTextBrandPrimary: ${c.accent} !important;

  /* Legacy LWC — backgrounds (surfaces, inputs, modals) */
  --lwc-colorBackgroundLight: ${c.surface} !important;
  --lwc-colorBackgroundShade: ${c.surfaceAlt || c.surfaceHover} !important;
  --lwc-colorBackgroundShadeDark: ${c.surfaceAlt || c.surfaceHover} !important;
  --lwc-colorBackgroundInput: ${isDark ? c.background : c.surface} !important;
  --lwc-colorBackgroundInputActive: ${isDark ? c.background : c.surface} !important;
  --lwc-colorBackgroundInputDisabled: ${c.surfaceAlt || c.surfaceHover} !important;
  --lwc-colorBackgroundInputError: ${c.surface} !important;
  --lwc-colorBackgroundInputSearch: ${inputSearchBg} !important;
  --lwc-colorBackgroundInputCheckbox: ${c.surface} !important;
  --lwc-colorBackgroundInputCheckboxSelected: ${brandBright} !important;
  --lwc-colorBackgroundModal: ${c.modalBg} !important;
  --lwc-colorBackgroundBackdropTint: ${c.modalBackdrop} !important;
  --lwc-colorBackgroundPill: ${c.pillBg} !important;

  /* Legacy LWC — button states */
  --lwc-colorBackgroundButtonBrandDisabled: ${buttonBrandDisabledBg} !important;
  --lwc-colorBackgroundButtonDefaultActive: ${c.surfaceHover} !important;
  --lwc-colorBackgroundButtonDefaultDisabled: ${c.surface} !important;
  --lwc-buttonColorBackgroundPrimary: ${c.buttonBrandBg} !important;
  --lwc-buttonColorBorderPrimary: ${buttonNeutralBorderDefault} !important;

  /* Legacy LWC — text (buttons, icons, actions) */
  --lwc-colorTextButtonBrandHover: ${c.buttonBrandText} !important;
  --lwc-colorTextButtonBrandDisabled: ${buttonBrandDisabledText} !important;
  --lwc-colorTextButtonDefault: ${buttonNeutralText} !important;
  --lwc-colorTextButtonDefaultHover: ${buttonNeutralText} !important;
  --lwc-colorTextButtonDefaultHint: ${c.textSecondary} !important;
  --lwc-colorTextButtonDefaultDisabled: ${c.textMuted} !important;
  --lwc-colorTextIconDefault: ${iconColor} !important;
  --lwc-colorTextIconDefaultHover: ${c.textPrimary} !important;
  --lwc-colorTextIconDefaultActive: ${c.accent} !important;
  --lwc-colorTextIconDefaultDisabled: ${c.textMuted} !important;
  --lwc-colorTextActionLabel: ${c.textSecondary} !important;
  --lwc-colorTextActionLabelActive: ${c.textPrimary} !important;
  --lwc-colorTextInputIcon: ${c.textSecondary} !important;

  /* Legacy LWC — borders */
  --lwc-colorBorderPrimary: ${c.border} !important;
  --lwc-colorBorderBrand: ${c.accent} !important;
  --lwc-colorBorderButtonBrand: ${c.buttonBrandBorder} !important;
  --lwc-colorBorderButtonBrandDisabled: ${c.buttonBrandDisabledBorder || 'transparent'} !important;
  --lwc-colorBorderButtonDefault: ${c.buttonNeutralBorder} !important;

  /* Component hooks — cards & inputs */
  --slds-c-card-color-background: ${c.surface} !important;
  --slds-c-card-color-border: ${c.border} !important;
  --slds-c-input-color-background: ${isDark ? c.background : c.surface} !important;
  --slds-c-input-color-border: ${c.borderInput} !important;
  --slds-c-input-color-border-focus: ${c.accent} !important;
  --slds-c-input-text-color: ${c.textPrimary} !important;

  /* Component hooks — buttons */
  --slds-c-button-brand-color-background: ${c.buttonBrandBg} !important;
  --slds-c-button-brand-color-border: ${c.buttonBrandBorder} !important;
  --slds-c-button-brand-color-background-hover: ${c.buttonBrandHover} !important;
  --slds-c-button-neutral-color-background: ${c.buttonNeutralBg} !important;
  --slds-c-button-neutral-color-border: ${c.buttonNeutralBorder} !important;
  --slds-c-button-neutral-color-background-hover: ${c.buttonNeutralHover} !important;
  --slds-c-button-neutral-color-border-hover: ${c.buttonNeutralBorder} !important;
  --slds-c-button-neutral-color-background-active: ${c.surfaceHover} !important;
  --slds-c-button-neutral-color-border-active: ${c.borderInput} !important;
  --slds-c-button-text-color-hover: ${c.textPrimary} !important;
  --slds-c-button-text-color-active: ${c.textPrimary} !important;

  /* Legacy LWC — gap tokens discovered 2026-04-12 */
  --lwc-colorBackgroundAlt2: ${c.surfaceAlt || c.background} !important;
  --lwc-colorBackgroundRowActive: ${c.surfaceSelection} !important;
  --lwc-colorBackgroundRowSelected: ${c.surfaceSelection} !important;
  --lwc-colorBackgroundNotification: ${c.surfaceHighlight} !important;
  --lwc-colorBackgroundToggleHover: ${c.surfaceHover} !important;
  --lwc-colorTextPrimary: ${c.textPrimary} !important;
  --lwc-colorTextLinkDisabled: ${c.textMuted} !important;
  --lwc-colorTextLinkActive: ${c.accentActive} !important;
  /* Kebab-case aliases SF uses alongside camelCase */
  --lwc-color-background: ${c.background} !important;
  --lwc-color-background-alt: ${c.surface} !important;
  --lwc-colorBackgroundDark: ${c.nav} !important;

  /* Component hooks — tabs */
  --slds-c-tabs-item-text-color: ${c.tabInactiveColor} !important;
  --slds-c-tabs-item-text-color-active: ${c.tabActiveColor} !important;
  --slds-c-tabs-item-color-border-hover: ${c.tabActiveBorder} !important;
  --slds-c-tabs-item-color-border-active: ${c.tabActiveBorder} !important;
}

/* ─── Base ───────────────────────────────────────────────────────────────── */

html,
body,
.desktop {
  background-color: ${c.background} !important;
  color: ${c.textPrimary} !important;${fx && fx.gridOverlay ? `
  background-image:
    repeating-linear-gradient(
      0deg,
      transparent,
      transparent 39px,
      rgba(${hexToRgb(c.accent)}, 0.02) 39px,
      rgba(${hexToRgb(c.accent)}, 0.02) 40px
    ),
    repeating-linear-gradient(
      90deg,
      transparent,
      transparent 39px,
      rgba(${hexToRgb(c.accent)}, 0.02) 39px,
      rgba(${hexToRgb(c.accent)}, 0.02) 40px
    ) !important;
  background-attachment: fixed !important;` : ''}
}

/* ─── Global Header ──────────────────────────────────────────────────────
 * Light themes with globalHeaderWhite force a white header so the SF logo
 * and slate icons stay legible.
 * Dark themes paint the header to match the nav band underneath — avoids
 * the jarring white strip above an otherwise dark app.
 * Light themes with globalHeaderWhite=false inherit SF's default white.
 */
${c.globalHeaderWhite && !isDark ? `
.slds-global-header,
.slds-global-header_container,
.forceSearchDesktopHeader {
  background-color: #ffffff !important;
  color: #2d2d2d !important;
}` : ''}

${isDark ? `
.slds-global-header,
.slds-global-header_container,
.forceSearchDesktopHeader {
  background-color: ${c.nav} !important;
  color: ${c.navText} !important;
}` : ''}

/* Global header controls — hamburger, environment switcher, edition badges.
 * Use header#oneHeader scoping (matches SF's actual nav DOM) for specificity
 * above SF defaults. Targets the three common "blended control" surfaces:
 *   - Icon-only buttons (hamburger, waffle, notifications)
 *   - Badges / edition pills (Developer Edition, Sandbox, Trial)
 *   - System message bar (gray-1 strip when present)
 * Recolor-only — preserves borders/radius/padding.
 */
header#oneHeader button,
header#oneHeader .slds-button,
.slds-global-header_container button,
.slds-global-header_container .slds-button {
  color: ${c.navIcon} !important;
}

header#oneHeader button svg,
header#oneHeader .slds-button svg,
header#oneHeader .slds-icon,
header#oneHeader .slds-button__icon,
.slds-global-header_container svg,
.slds-global-header_container .slds-icon,
.slds-global-header_container .slds-button__icon {
  fill: ${c.navIcon} !important;
  color: ${c.navIcon} !important;
}

/* Environment / edition pill (Developer Edition, Sandbox, Trial).
 * Use a clear accent-tint so it reads as a distinct pill against the header. */
header#oneHeader .slds-badge,
header#oneHeader .slds-badge_inverse,
header#oneHeader .slds-badge--inverse,
header#oneHeader .slds-badge_lightest,
.slds-global-header_container .slds-badge,
.slds-global-header_container .slds-badge_inverse,
.slds-global-header_container .slds-badge--inverse,
.slds-global-header_container .slds-badge_lightest,
header#oneHeader .slds-pill,
.slds-global-header_container .slds-pill {
  background-color: ${c.accentLight} !important;
  color: ${c.accent} !important;
  border: 1px solid ${c.navBorder} !important;
}

/* System message bar (org-edition banner, trial countdown, etc.) */
header#oneHeader .oneSystemMessage,
header#oneHeader .oneSystemMessage.slds-color__background_gray-1,
.slds-global-header_container .oneSystemMessage {
  background-color: ${c.surfaceHighlight || c.accentLight} !important;
  color: ${c.navText} !important;
  border-bottom: 1px solid ${c.navBorder} !important;
}

${isDark || !c.globalHeaderWhite ? `
/* Search box in header — themed for dark or non-white-header themes */
.slds-global-header .slds-input,
.slds-global-header input[type="search"],
.forceSearchDesktopHeader input,
.slds-global-header .slds-form-element__control input {
  background-color: ${c.searchBg || c.surface} !important;
  color: ${c.searchText || c.textPrimary} !important;
  border-color: ${c.searchBorder || c.border} !important;
  border-radius: 6px !important;${fx && fx.glowOnHover ? `
  box-shadow: 0 0 6px ${c.accentLight} !important;` : ''}
}

.slds-global-header .slds-input::placeholder,
.slds-global-header input::placeholder {
  color: ${c.searchPlaceholder || c.textPlaceholder} !important;
}

.slds-global-header .slds-input:focus,
.slds-global-header input:focus {
  border-color: ${c.searchFocusBorder || c.accent} !important;
  box-shadow: ${c.searchFocusShadow || c.focusRing} !important;
}` : ''}

/* ─── Navigation ─────────────────────────────────────────────────────────── */

.oneGlobalNav,
one-app-nav-bar,
.navexConsoleTabBar,
[class*="globalNavigation"],
.slds-context-bar {
  background-color: ${c.nav} !important;
  border-bottom: 1px solid ${c.navBorder} !important;${fx && fx.navBoxShadow ? `
  box-shadow: ${fx.navBoxShadow} !important;` : ''}
}

.slds-context-bar__item,
.navexConsoleTabItem,
.oneConsoleTabItem {
  color: ${c.navText} !important;
}

.slds-context-bar__item:hover,
.navexConsoleTabItem:hover {
  background-color: ${c.navHover} !important;${c.navActiveText !== c.navText ? `
  color: ${c.navActiveText} !important;` : ''}
}

/* Active nav tab — paint ONLY the outer list item.
 * SF stacks three possible layers on an active tab (.slds-context-bar__item,
 * one-app-nav-bar-item-root wrapper, inner <a>). Painting more than one layer
 * produces a "chip inside a bubble" double-highlight. Keep the background on
 * the outer <li> and null every inner layer, including SF's own SLDS tokens,
 * so the highlight reads as ONE pill. */
.slds-context-bar__item.slds-is-active,
.slds-context-bar__item.slds-is-active.slds-is-unsaved,
.navexConsoleTabItem.active {
  background-color: ${c.navActive} !important;
  border-bottom-color: ${c.navActiveBorder} !important;${fx && fx.navActiveBoxShadow ? `
  box-shadow: ${fx.navActiveBoxShadow} !important;` : ''}
  color: ${c.navActiveText} !important;
}

/* Kill the underline pseudo-elements on active tab */
.slds-context-bar__item.slds-is-active::before,
.slds-context-bar__item.slds-is-active::after,
one-app-nav-bar-item-root.slds-is-active::before,
one-app-nav-bar-item-root.slds-is-active::after,
.slds-context-bar__item.slds-is-active a::before,
.slds-context-bar__item.slds-is-active a::after,
one-app-nav-bar-item-root.slds-is-active a::before,
one-app-nav-bar-item-root.slds-is-active a::after {
  background-color: ${c.navActiveBorder} !important;
  background: ${c.navActiveBorder} !important;
  border-color: ${c.navActiveBorder} !important;
}

/* Null ALL inner active-tab backgrounds — prevents double-chip visual.
 * Also override SLDS/LWC tokens SF uses internally for the active state,
 * so customer orgs on SLDS 2 (Cosmos) don't re-introduce the inner pill. */
.slds-context-bar__item.slds-is-active one-app-nav-bar-item-root,
one-app-nav-bar-item-root.slds-is-active,
one-app-nav-bar-item-root.navItem.slds-is-active,
.slds-context-bar__item.slds-is-active .slds-context-bar__label-action,
.slds-context-bar__item.slds-is-active a,
one-app-nav-bar-item-root.slds-is-active a,
one-app-nav-bar-item-root.slds-is-active a.dndItem,
one-app-nav-bar-item-root.slds-is-active .slds-context-bar__label-action,
.slds-context-bar a[aria-current="page"] {
  color: ${c.navActiveText} !important;
  background-color: transparent !important;
  --slds-c-context-bar-item-color-background-active: transparent !important;
  --lwc-brandNavigationColorBackgroundActive: transparent !important;
}

/* Nav text and icons */
.slds-context-bar__label-action,
.slds-context-bar__icon-action,
.slds-context-bar .slds-icon {
  color: ${c.navIcon} !important;
  fill: ${c.navIcon} !important;
}

/* App launcher button */
.slds-context-bar__app-name,
.appLauncherButton {
  color: ${c.navAppName} !important;
  border-right: 1px solid ${c.navAppBorder} !important;${fx ? `
  text-shadow: 0 0 8px ${c.accentLight} !important;` : ''}
}

/* App launcher waffle dots — target individual dots, not the container */
.slds-icon-waffle .slds-r1,
.slds-icon-waffle .slds-r2,
.slds-icon-waffle .slds-r3,
.slds-icon-waffle .slds-r4,
.slds-icon-waffle .slds-r5,
.slds-icon-waffle .slds-r6,
.slds-icon-waffle .slds-r7,
.slds-icon-waffle .slds-r8,
.slds-icon-waffle .slds-r9 {
  background-color: ${c.navWaffleDot} !important;
}

/* ─── Main Content ───────────────────────────────────────────────────────── */

.oneContent,
.oneWorkspace,
.flexipageBody,
.onesetupSetupLayout,
.setupcontent {
  background-color: ${fx && fx.gridOverlay ? 'transparent' : c.background} !important;
}

/* ─── Page Headers ───────────────────────────────────────────────────────── */

.slds-page-header,
.forceListViewManager .listViewManager,
[class*="pageHeader"] {
  background-color: ${c.surface} !important;
  border-bottom: 1px solid ${c.border} !important;
  box-shadow: ${isDark ? '0 1px 0 rgba(255, 255, 255, 0.04)' : '0 1px 3px rgba(0, 0, 0, 0.06)'} !important;${fx ? `
  box-shadow: 0 1px 20px rgba(${hexToRgb(c.accent)}, 0.06) !important;` : ''}
}

.slds-page-header__title,
.slds-page-header__name-title {
  color: ${c.textPrimary} !important;${fx ? `
  text-shadow: 0 0 12px rgba(${hexToRgb(c.accent)}, 0.3) !important;` : ''}
}

.slds-page-header__meta-text {
  color: ${c.textSecondary} !important;
}

/* ─── Cards ──────────────────────────────────────────────────────────────── */

/* Cards — border only on .slds-card itself, not inner body/footer */
.slds-card,
.forceRecordCard {
  background-color: ${c.surface} !important;
  border-color: ${c.border} !important;
  box-shadow: ${isDark ? '0 1px 4px rgba(0, 0, 0, 0.2)' : '0 1px 4px rgba(0, 0, 0, 0.06)'} !important;${isDark ? `
  color: ${c.textPrimary} !important;` : ''}${fx ? `
  box-shadow: 0 0 20px rgba(${hexToRgb(c.accent)}, 0.06), inset 0 0 40px rgba(0, 0, 0, 0.2) !important;` : ''}
}

.slds-card__body,
.slds-card__footer {
  background-color: ${c.surface} !important;${isDark ? `
  color: ${c.textPrimary} !important;` : ''}
}
${fx ? `
.slds-card:hover {
  border-color: ${fx.cardHoverBorder} !important;
  box-shadow: ${fx.cardHoverShadow} !important;
}` : ''}

.slds-card__header {
  background-color: ${c.surface} !important;
  border-bottom-color: ${isDark ? 'rgba(255,255,255,0.06)' : c.border} !important;
}

/* ─── Buttons ────────────────────────────────────────────────────────────── */

.slds-button_brand,
.slds-button--brand {
  background-color: ${c.buttonBrandBg} !important;
  border: 1px solid ${c.buttonBrandBorder} !important;
  color: ${c.buttonBrandText} !important;${fx ? `
  text-shadow: 0 0 8px rgba(${hexToRgb(c.accent)}, 0.5) !important;
  box-shadow: 0 0 10px rgba(${hexToRgb(c.accent)}, 0.15), inset 0 0 10px rgba(${hexToRgb(c.accent)}, 0.05) !important;` : ''}
}

.slds-button_brand:hover,
.slds-button--brand:hover {
  background-color: ${c.buttonBrandHover} !important;
  border-color: ${c.buttonBrandHover} !important;${fx ? `
  box-shadow: 0 0 20px rgba(${hexToRgb(c.accent)}, 0.3), inset 0 0 20px rgba(${hexToRgb(c.accent)}, 0.1) !important;` : ''}
}

.slds-button_neutral,
.slds-button--neutral {
  background-color: ${c.buttonNeutralBg} !important;
  border-color: ${c.buttonNeutralBorder} !important;
  color: ${c.buttonNeutralText} !important;
}

.slds-button_neutral:hover,
.slds-button--neutral:hover {
  background-color: ${c.buttonNeutralHover} !important;
}

/* ─── Form Elements ──────────────────────────────────────────────────────── */

.slds-input,
.slds-textarea,
.slds-select,
.slds-combobox__form-element,
.slds-has-input-focus .slds-input {
  background-color: ${isDark ? c.background : c.surface} !important;
  border-color: ${c.borderInput} !important;
  color: ${c.textPrimary} !important;
}

.slds-input:focus,
.slds-textarea:focus,
.slds-select:focus {
  border-color: ${c.accent} !important;
  box-shadow: ${isDark
    ? `0 0 0 3px rgba(${hexToRgb(c.accent)}, 0.2)${fx ? `, 0 0 12px rgba(${hexToRgb(c.accent)}, 0.15)` : ''}`
    : `0 0 0 3px rgba(${hexToRgb(c.accent)}, 0.2)`
  } !important;
  outline: none !important;
}

.slds-input::placeholder,
.slds-textarea::placeholder {
  color: ${c.textPlaceholder} !important;
}

.slds-form-element__label {
  color: ${c.textSecondary} !important;
  font-weight: 500 !important;
}

/* ─── Tables ─────────────────────────────────────────────────────────────── */

.slds-table {
  background-color: ${c.surface} !important;
  border: 1px solid ${c.border} !important;
}

.slds-table thead th,
.slds-table thead td {
  background-color: ${c.tableHeaderBg} !important;
  color: ${c.tableHeaderText} !important;
  border-bottom: ${isDark ? '2px' : '2px'} solid ${c.border} !important;
  font-weight: 600 !important;${fx ? `
  text-transform: uppercase !important;
  font-size: 11px !important;
  letter-spacing: 0.08em !important;
  text-shadow: 0 0 8px rgba(${hexToRgb(c.accent)}, 0.4) !important;` : ''}
}

.slds-table tbody tr {
  background-color: ${c.surface} !important;
  border-bottom: 1px solid ${c.tableBorderRow} !important;
  color: ${c.textPrimary} !important;
}

.slds-table tbody tr:nth-child(even) {
  background-color: ${c.tableAltRow} !important;
}

.slds-table tbody tr:hover {
  background-color: ${c.tableHoverRow} !important;${fx ? `
  box-shadow: inset 0 0 20px rgba(${hexToRgb(c.accent)}, 0.04) !important;` : ''}
}

.slds-table td,
.slds-table th {
  color: ${c.textPrimary} !important;
  border-right: 1px solid ${c.tableColBorder} !important;
}

/* ─── Modals ─────────────────────────────────────────────────────────────── */

.slds-modal__container {
  background-color: ${c.modalBg} !important;
  border: 1px solid ${c.border} !important;
  box-shadow: ${c.modalShadow} !important;
}

.slds-modal__header {
  background-color: ${c.modalHeaderBg} !important;
  border-bottom: 1px solid ${c.border} !important;
  color: ${c.textPrimary} !important;
}

.slds-modal__content {
  background-color: ${c.modalBg} !important;
  color: ${c.textPrimary} !important;
}

.slds-modal__footer {
  background-color: ${c.modalFooterBg} !important;
  border-top: 1px solid ${c.border} !important;
}

.slds-backdrop {
  background-color: ${c.modalBackdrop} !important;
}

/* App Launcher — uses viewport-filling overlay, not a standard modal.
 * Only recolor the inner modal container + contents; leave the
 * <one-app-launcher-modal> wrapper and its .slds-modal child alone —
 * they carry the backdrop/overlay behavior and should inherit SF's
 * defaults plus the .slds-backdrop rule below. */
one-app-launcher-modal .modal-container,
one-app-launcher-modal .slds-modal__container {
  background-color: ${c.modalBg} !important;
  max-height: 90vh !important;
  height: auto !important;
}

one-app-launcher-modal .modal-body,
one-app-launcher-modal .slds-modal__content {
  background-color: ${c.modalBg} !important;
  max-height: none !important;
}

one-app-launcher-modal .modal-header,
one-app-launcher-modal .slds-modal__header {
  background-color: ${c.modalHeaderBg} !important;
  position: relative !important;
}

/* App Launcher backdrop — use the theme's standard modal backdrop tint */
one-app-launcher-modal + .slds-backdrop,
one-app-launcher-modal ~ .slds-backdrop {
  background-color: ${c.modalBackdrop} !important;
}

/* ─── Dropdowns & Popovers ───────────────────────────────────────────────── */

.slds-dropdown,
.slds-dropdown__list {
  background-color: ${c.dropdownBg} !important;
  border: 1px solid ${c.border} !important;
  box-shadow: ${isDark ? '0 8px 24px rgba(0, 0, 0, 0.5)' : '0 4px 16px rgba(0, 0, 0, 0.10)'} !important;${fx ? `
  box-shadow: 0 0 30px rgba(${hexToRgb(c.accent)}, 0.12), 0 8px 24px rgba(0, 0, 0, 0.6) !important;` : ''}
}

.slds-dropdown__item > a,
.slds-dropdown__item > span {
  color: ${c.textPrimary} !important;
}

.slds-dropdown__item:hover > a,
.slds-dropdown__item:hover > span,
.slds-dropdown__item:focus > a {
  background-color: ${c.dropdownItemHoverBg} !important;
  color: ${c.dropdownItemHoverText} !important;
}

.slds-popover {
  background-color: ${c.dropdownBg} !important;
  border: 1px solid ${c.border} !important;
  box-shadow: ${isDark ? '0 8px 24px rgba(0, 0, 0, 0.45)' : '0 4px 16px rgba(0, 0, 0, 0.10)'} !important;
  color: ${c.textPrimary} !important;
}

/* ─── Tabs ───────────────────────────────────────────────────────────────── */

.slds-tabs_default__nav,
.slds-tabs--default__nav {
  border-bottom: 2px solid ${c.tabNavBorder} !important;
  background-color: transparent !important;
}

.slds-tabs_default__item,
.slds-tabs--default__item {
  color: ${c.tabInactiveColor} !important;
}

.slds-tabs_default__item.slds-is-active,
.slds-tabs--default__item.slds-active {
  color: ${c.tabActiveColor} !important;
  border-bottom-color: ${c.tabActiveBorder} !important;${fx ? `
  text-shadow: 0 0 10px rgba(${hexToRgb(c.accent)}, 0.5) !important;` : ''}
}

/* Override SF's ::after pseudo-element tab indicator */
.slds-tabs_default__item.slds-is-active::after,
.slds-tabs--default__item.slds-active::after {
  background-color: ${c.tabActiveBorder} !important;
}

.slds-tabs_default__content,
.slds-tabs--default__content {
  background-color: ${c.tabContentBg} !important;
}

/* ─── Pills & Badges ─────────────────────────────────────────────────────── */

.slds-pill {
  background-color: ${c.pillBg} !important;
  border: 1px solid ${c.pillBorder} !important;
  color: ${c.pillText} !important;
}

.slds-badge {
  background-color: ${c.badgeBg} !important;
  color: ${c.badgeText} !important;${c.badgeBorder !== 'none' ? `
  border: ${c.badgeBorder} !important;` : ''}${fx ? `
  text-shadow: 0 0 6px rgba(${hexToRgb(c.accent)}, 0.5) !important;` : ''}
}

/* ─── Scrollbars ─────────────────────────────────────────────────────────── */

::-webkit-scrollbar {
  width: ${fx ? '6px' : '8px'} !important;
  height: ${fx ? '6px' : '8px'} !important;
}

::-webkit-scrollbar-track {
  background: ${c.scrollTrack} !important;${fx ? `
  border-left: 1px solid rgba(${hexToRgb(c.accent)}, 0.06) !important;` : ''}
}

::-webkit-scrollbar-thumb {
  background: ${c.scrollThumb} !important;
  border-radius: ${fx ? '3px' : '4px'} !important;
}

::-webkit-scrollbar-thumb:hover {
  background: ${c.scrollThumbHover} !important;${fx && fx.glowOnHover ? `
  box-shadow: 0 0 6px rgba(${hexToRgb(c.accent)}, 0.3) !important;` : ''}
}

/* ─── Record Detail ──────────────────────────────────────────────────────── */

.forceOutputField,
.slds-form-element__static {
  color: ${c.textPrimary} !important;
}

/* ─── Sidebar / Panel ────────────────────────────────────────────────────── */

.slds-panel,
.slds-split-view_container {
  background-color: ${c.panelBg} !important;
  border-right: 1px solid ${c.panelBorder} !important;
}

/* ─── Links ──────────────────────────────────────────────────────────────── */

a,
.slds-truncate a,
.forceOutputLookup a {
  color: ${c.link} !important;${fx && fx.linkTextShadow ? `
  text-shadow: ${fx.linkTextShadow} !important;` : ''}
}

a:hover {
  color: ${c.linkHover} !important;${fx && fx.linkHoverTextShadow ? `
  text-shadow: ${fx.linkHoverTextShadow} !important;` : ''}
}

/* ─── Setup Pages ────────────────────────────────────────────────────────── */

.setupcontent,
.slds-setup-assistant,
.setup-page,
[class*="setupLayout"],
.onesetupSetupLayout,
.setupTabContent,
.slds-setup-summary,
.forceSetupDesktop,
.bodyDiv,
.setupHasMenu,
.contentRegion,
.contentWrapper,
.individualPalette,
.bPageBlock,
.pbBody,
.pbSubsection {
  background-color: ${c.background} !important;
  color: ${c.textPrimary} !important;
}

/* Legacy Visualforce-backed Setup pages: these load in iframes from
   *.visualforce.com and have a totally different DOM (no Lightning shell).
   Paint the html/body of those iframes directly so the user doesn't see a
   bright white block embedded inside their themed Setup page. */
html.setupBody,
body.setupBody,
body.setupTab,
body[class*="setup"],
.setupHelpContent,
.setupBodyDiv {
  background-color: ${c.background} !important;
  color: ${c.textPrimary} !important;
}

.setupBody a,
.setupBody .topNav,
.setupBody .secondaryPalette {
  color: ${c.textPrimary} !important;
}

.setupBody table,
.setupBody .list,
.setupBody .pbBody,
.setupBody .pbSubsection,
.setupBody .pbHeader {
  background-color: ${c.surface} !important;
  border-color: ${c.border} !important;
  color: ${c.textPrimary} !important;
}

/* ─── Reports ────────────────────────────────────────────────────────────── */

.report-container,
.reportOutput,
[class*="reportPage"],
.slds-report,
.forceReportOutput,
.reportHeader {
  background-color: ${c.background} !important;
  color: ${c.textPrimary} !important;
}

/* ─── Console / Service Console ──────────────────────────────────────────── */

.navexConsoleContent,
.workspaceManager,
.split-view,
.slds-split-view,
[class*="console"] {
  background-color: ${c.background} !important;
  color: ${c.textPrimary} !important;
}

/* ─── Record Page Header / Highlights ────────────────────────────────────── */

.highlights,
.forceHighlightsStencilDesktop,
.forceRecordLayout,
.forceHighlightsPanel,
.slds-page-header--record-home,
.slds-page-header_record-home,
.flexipageHeader,
.record-page-decorator,
.recordHomeTemplate,
.forceHighlightsLayout {
  background-color: ${c.background} !important;
  color: ${c.textPrimary} !important;
  border-color: ${c.border} !important;
  box-shadow: ${isDark ? '0 1px 3px rgba(0, 0, 0, 0.15)' : '0 1px 3px rgba(0, 0, 0, 0.06)'} !important;
}

/* Record page full body background */
.flexipagePage,
.flexipage-template,
.uiTabBar + .tabContent,
.forceRecordFlexiPage {
  background-color: ${c.background} !important;
}

/* ─── Path / Stage Path ─────────────────────────────────────────────────── */

/* Path structural containers — recolor, keep structure */
.slds-path,
.slds-path__scroller,
.slds-path__track,
.slds-path__wrap,
.slds-path__coach,
.slds-path__nav,
.slds-path__scroller-container,
.slds-path__scroller_inner,
.slds-path__scroll-controls,
.slds-grid.slds-path__track,
.pathAssistantContainer,
.forcePathAssistant,
lightning-sales-path,
records-lwc-highlights-panel,
.runtime_sales_pathassistantPathAssistantTabSet,
.runtime_sales_pathassistantPathAssistantHeader,
.uiScroller.slds-path__scroller,
[class*="pathAssistant"],
[class*="PathAssistant"],
[class*="salesPath"],
[class*="SalesPath"] {
  background-color: ${c.surface} !important;
  color: ${c.textPrimary} !important;
}

/* Path scroller inner wrapper */
.slds-path__scroller .scroller,
.slds-path__scroller .slds-path__scroller_inner {
  background-color: ${c.surface} !important;
}

/* The slds-card wrapping the path — recolor, keep structure */
body .pathOriginal .slds-card,
body .pathOriginal .slds-card__body,
body .pathOriginal .slds-card__body_inner,
body .runtime_sales_pathassistantPathAssistant .slds-card,
body .runtime_sales_pathassistantPathAssistant .slds-card__body,
body .runtime_sales_pathassistantPathAssistant .slds-card__body_inner,
body .runtime_sales_pathassistantPathAssistant > article,
body .forcePathAssistant .slds-card,
body .forcePathAssistant .slds-card__body,
body .forcePathAssistant .slds-card__body_inner {
  background-color: ${c.surface} !important;
  border-color: ${c.border} !important;
  box-shadow: ${isDark ? '0 1px 4px rgba(0, 0, 0, 0.2)' : '0 1px 4px rgba(0, 0, 0, 0.06)'} !important;
}

/* Path items — boosted specificity with body prefix */
body .slds-path__item,
body .slds-path__item .slds-path__link,
body .slds-path__item a.slds-path__link {
  background-color: ${c.surfaceAlt} !important;
}

body .slds-path__item.slds-is-complete,
body .slds-path__item.slds-is-complete .slds-path__link,
body .slds-path__item.slds-is-complete a.slds-path__link {
  background-color: ${c.accent} !important;
}

body .slds-path__item.slds-is-current,
body .slds-path__item.slds-is-current .slds-path__link,
body .slds-path__item.slds-is-current a.slds-path__link {
  background-color: ${c.accent} !important;
}

body .slds-path__item.slds-is-incomplete,
body .slds-path__item.slds-is-incomplete .slds-path__link,
body .slds-path__item.slds-is-incomplete a.slds-path__link {
  background-color: ${c.surfaceAlt} !important;
}

/* Path chevrons — SLDS uses skewed ::before/::after with background, NOT border triangles */
/* Each state must set background on BOTH the item AND its pseudo-elements */

/* Incomplete (default) — item + pseudo-elements */
body .slds-path__item::before,
body .slds-path__item::after {
  background: ${c.surfaceAlt} !important;
}

body .slds-path__item.slds-is-incomplete::before,
body .slds-path__item.slds-is-incomplete::after {
  background: ${c.surfaceAlt} !important;
}

/* Complete */
body .slds-path__item.slds-is-complete::before,
body .slds-path__item.slds-is-complete::after {
  background: ${c.accent} !important;
}

/* Current */
body .slds-path__item.slds-is-current::before,
body .slds-path__item.slds-is-current::after {
  background-color: ${c.accent} !important;
  background-image: none !important;
}

/* Active / selected — MUST come after incomplete to win specificity */
/* Handles both .slds-is-active alone AND .slds-is-incomplete.slds-is-active */
body .slds-path__item.slds-is-active,
body .slds-path__item.slds-is-active .slds-path__link,
body .slds-path__item.slds-is-active a.slds-path__link,
body .slds-path__item.slds-is-incomplete.slds-is-active,
body .slds-path__item.slds-is-incomplete.slds-is-active .slds-path__link,
body .slds-path__item.slds-is-incomplete.slds-is-active a.slds-path__link,
body .slds-path__item [aria-selected="true"] {
  background-color: ${c.accentHover} !important;
  color: ${c.buttonBrandText} !important;
}

body .slds-path__item.slds-is-active::before,
body .slds-path__item.slds-is-active::after,
body .slds-path__item.slds-is-incomplete.slds-is-active::before,
body .slds-path__item.slds-is-incomplete.slds-is-active::after {
  background: ${c.accentHover} !important;
}

/* Hover — incomplete items */
.slds-path__item:hover,
.slds-path__item:hover .slds-path__link {
  background-color: ${c.surfaceHover} !important;
}

.slds-path__item:hover::before,
.slds-path__item:hover::after {
  background: ${c.surfaceHover} !important;
}

/* Hover — complete/current items */
.slds-path__item.slds-is-complete:hover,
.slds-path__item.slds-is-complete:hover .slds-path__link,
.slds-path__item.slds-is-current:hover,
.slds-path__item.slds-is-current:hover .slds-path__link {
  background-color: ${c.accentHover} !important;
}

.slds-path__item.slds-is-complete:hover::before,
.slds-path__item.slds-is-complete:hover::after,
.slds-path__item.slds-is-current:hover::before,
.slds-path__item.slds-is-current:hover::after {
  background: ${c.accentHover} !important;
}

/* Won (Closed Won) */
body .slds-path__item.slds-is-won,
body .slds-path__item.slds-is-won .slds-path__link,
body .slds-path__item.slds-is-won a.slds-path__link {
  background-color: ${c.success} !important;
}

body .slds-path__item.slds-is-won::before,
body .slds-path__item.slds-is-won::after {
  background: ${c.success} !important;
}

body .slds-path__item.slds-is-won .slds-path__title {
  color: #ffffff !important;
}

/* Lost (Closed Lost) */
body .slds-path__item.slds-is-lost,
body .slds-path__item.slds-is-lost .slds-path__link,
body .slds-path__item.slds-is-lost a.slds-path__link {
  background-color: ${c.error} !important;
}

body .slds-path__item.slds-is-lost::before,
body .slds-path__item.slds-is-lost::after {
  background: ${c.error} !important;
}

body .slds-path__item.slds-is-lost .slds-path__title {
  color: #ffffff !important;
}

/* Path text colors */
.slds-path__title {
  color: ${c.textPrimary} !important;
}

.slds-path__item.slds-is-complete .slds-path__title,
.slds-path__item.slds-is-current .slds-path__title,
.slds-path__item.slds-is-active .slds-path__title {
  color: ${c.buttonBrandText} !important;
}

/* Path stage icon (checkmark on completed) */
.slds-path__stage {
  color: ${c.buttonBrandText} !important;
}

/* ─── Related List Cards (right sidebar) ─────────────────────────────────── */

/* Related list containers — background only, cards handle their own borders */
.forceRelatedListContainer,
.forceRelatedListSingleContainer {
  background-color: ${c.background} !important;
}

/* Related list inner headers — no extra borders */
.slds-page-header_joined,
.slds-page-header_bleed,
.slds-page-header.slds-page-header_joined {
  border-color: transparent !important;
  box-shadow: none !important;
}

/* ─── Profile Icon / Global Actions (top right) ─────────────────────────── */
/* Keep white header's action icons visible — don't override their colors */

.slds-global-actions__item > button,
.slds-global-actions__item > span,
.slds-global-actions__item > div > button {
  background-color: transparent !important;
}

${c.globalHeaderWhite && !isDark ? `
/* Light white header: slate icons for legibility on white */
.slds-global-header .slds-global-header__icon,
.slds-global-header .slds-button__icon,
.slds-global-header .forceIcon .slds-icon,
.slds-global-actions .slds-icon {
  fill: #54698d !important;
  color: #54698d !important;
}` : ''}

${isDark ? `
/* Dark header: icons match theme navIcon for visibility on dark surfaces */
.slds-global-header .slds-global-header__icon,
.slds-global-header .slds-button__icon,
.slds-global-header .forceIcon .slds-icon,
.slds-global-actions .slds-icon {
  fill: ${c.navIcon} !important;
  color: ${c.navIcon} !important;
}` : ''}

/* Profile avatar container — keep structure, just hide border visually */
.slds-avatar,
.forceSocialPhoto,
.photoContainer {
  border-color: transparent !important;
}
` + _generateTypographyCSS(typo);
}

/**
 * Convert hex color to "R, G, B" string for use in rgba().
 * Returns a fallback string if parsing fails.
 * @param {string} hex
 * @returns {string}
 */
function hexToRgb(hex) {
  if (!hex || typeof hex !== 'string') return '74, 111, 165';
  // Strip leading # and handle short hex
  const clean = hex.replace('#', '');
  if (clean.length === 3) {
    const r = parseInt(clean[0] + clean[0], 16);
    const g = parseInt(clean[1] + clean[1], 16);
    const b = parseInt(clean[2] + clean[2], 16);
    return `${r}, ${g}, ${b}`;
  }
  if (clean.length === 6) {
    const r = parseInt(clean.slice(0, 2), 16);
    const g = parseInt(clean.slice(2, 4), 16);
    const b = parseInt(clean.slice(4, 6), 16);
    return `${r}, ${g}, ${b}`;
  }
  return '74, 111, 165';
}

// ────────────────────────────────────────────────────────────────────────────
// Favicon rendering — folded into the theme engine so a theme is one config
// that produces one pair of artifacts: { css, faviconSvg }. Single source of
// truth for icon library + SVG builder; consumed by renderTheme() below,
// by Studio (options.js) for live preview, and by the CI preset rebuild.
//
// Favicon glyphs render at 16px in browser tabs — they need to read as bold
// solid marks. No opacity on the paths; transparency is owned by the
// shape=none background, not the glyph.
// ────────────────────────────────────────────────────────────────────────────

const FAVICON_ICONS = [
  { id: 'connectry', label: 'Connectry', svg: '<circle cx="8" cy="16" r="4" fill="white"/><line x1="12" y1="16" x2="20" y2="16" stroke="white" stroke-width="2" stroke-linecap="round"/><circle cx="24" cy="16" r="4" fill="white"/>' },
  { id: 'cloud',     label: 'Cloud',     svg: '<circle cx="10" cy="19" r="5" fill="white"/><circle cx="16" cy="14" r="6" fill="white"/><circle cx="22" cy="19" r="5" fill="white"/><rect x="10" y="19" width="12" height="5" fill="white"/>' },
  { id: 'snowflake', label: 'Snowflake', svg: '<path d="M16 4v24M4 16h24M8 8l16 16M24 8L8 24" stroke="white" stroke-width="2" stroke-linecap="round"/><circle cx="16" cy="16" r="2" fill="white"/>' },
  { id: 'flame',     label: 'Flame',     svg: '<path d="M16 4c0 6-6 8-6 14a6 6 0 0012 0c0-6-6-8-6-14z" fill="white"/>' },
  { id: 'moon',      label: 'Moon',      svg: '<path d="M20 6a10 10 0 11-8 20 12 12 0 008-20z" fill="white"/>' },
  { id: 'bolt',      label: 'Bolt',      svg: '<path d="M18 4L8 18h7l-3 10 10-14h-7l3-10z" fill="white"/>' },
  { id: 'leaf',      label: 'Leaf',      svg: '<path d="M8 24C8 12 16 4 28 4c0 12-8 20-20 20z" fill="white"/>' },
  { id: 'star',      label: 'Star',      svg: '<path d="M16 4l3.5 8 8.5 1-6.5 6 2 8.5L16 23l-7.5 4.5 2-8.5L4 13l8.5-1z" fill="white"/>' },
  { id: 'diamond',   label: 'Diamond',   svg: '<path d="M16 3l11 13-11 13L5 16z" fill="white"/>' },
  { id: 'shield',    label: 'Shield',    svg: '<path d="M16 3L5 8v7c0 7 5 12 11 14 6-2 11-7 11-14V8L16 3z" fill="white"/>' },
  { id: 'heart',     label: 'Heart',     svg: '<path d="M16 28s-10-6-10-14a5.5 5.5 0 0111 0 5.5 5.5 0 0111 0c0 8-12 14-12 14z" fill="white" transform="translate(0,-2)"/>' },
  { id: 'waves',     label: 'Waves',     svg: '<path d="M4 12c4-3 8 3 12 0s8 3 12 0M4 18c4-3 8 3 12 0s8 3 12 0" stroke="white" stroke-width="2.5" stroke-linecap="round" fill="none"/>' },
];

const FAVICON_DEFAULT_CONFIG = { shape: 'circle', color: '#4A6FA5', icon: 'connectry', iconColor: '#ffffff' };

/**
 * Build a theme favicon SVG string.
 * Pure function — safe to call in any context (service worker, Node/CI, DOM).
 *
 * @param {{shape?: string, color?: string, icon?: string, iconColor?: string}} config
 * @param {number} [size=32] Rendered width/height in px. viewBox is always 32.
 * @returns {string} '<svg …>…</svg>'
 */
function renderFavicon(config, size) {
  const shape    = (config && config.shape)    || FAVICON_DEFAULT_CONFIG.shape;
  const color    = (config && config.color)    || FAVICON_DEFAULT_CONFIG.color;
  const iconId   = (config && config.icon)     || FAVICON_DEFAULT_CONFIG.icon;
  // When there's no background, an unspecified iconColor falls back to the
  // bg color so the glyph stays visible on a transparent tab — preserves
  // the pre-iconColor behaviour users were relying on.
  const iconColor = (config && config.iconColor)
    || (shape === 'none' ? color : FAVICON_DEFAULT_CONFIG.iconColor);
  const dim = size || 32;

  const icon = FAVICON_ICONS.find(i => i.id === iconId) || FAVICON_ICONS[0];
  let bg = '';
  if (shape === 'circle')  bg = `<circle cx="16" cy="16" r="15" fill="${color}"/>`;
  else if (shape === 'rounded') bg = `<rect x="1" y="1" width="30" height="30" rx="6" fill="${color}"/>`;
  else if (shape === 'square')  bg = `<rect x="1" y="1" width="30" height="30" rx="1" fill="${color}"/>`;
  // shape === 'none' leaves bg empty (transparent tab background).

  const glyph = icon.svg.replace(/white/g, iconColor);
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="${dim}" height="${dim}">${bg}${glyph}</svg>`;
}

/**
 * Resolve the default favicon config for a theme that hasn't set one.
 * Monogram system — every preset uses the Connectry glyph tinted with its
 * accent, consistent branding with the theme accent as the only differentiator.
 */
function defaultFaviconForTheme(themeId, accent) {
  return {
    shape: 'circle',
    color: accent || FAVICON_DEFAULT_CONFIG.color,
    icon: 'connectry',
  };
}


// ────────────────────────────────────────────────────────────────────────────
// renderTheme — the V2-portable primitive. Given a full theme object, returns
// both artifacts the runtime needs. CI calls this per preset; Studio calls
// this per save; a future Supabase Edge Function will call this server-side.
//
// Theme input shape:
//   { id, colors, typography?, favicon? }
// Returns:
//   { css, faviconSvg }
// ────────────────────────────────────────────────────────────────────────────

function renderTheme(theme) {
  if (!theme || !theme.colors) {
    throw new Error('renderTheme: theme must have a .colors object');
  }
  const css = generateThemeCSS(theme);
  const faviconConfig = theme.favicon || defaultFaviconForTheme(theme.id, theme.colors.accent);
  const faviconSvg = renderFavicon(faviconConfig, 32);
  return { css, faviconSvg };
}


// Browser-context globals.
//   self.ConnectryThemer  — canonical engine surface (renderTheme, renderFavicon, ...)
//   self.ConnectryFavicon — backward-compat shim for the old core/favicon/engine.js
//                           API. Keeps existing call sites in content.js, options.js,
//                           popup.js working unchanged during and after A2.
// When themes/engine.js is loaded in a surface (options, popup) or Node (CI), both
// globals populate. core/favicon/engine.js can be deleted — ConnectryFavicon still
// exists because we re-export its shape here.
if (typeof self !== 'undefined') {
  self.ConnectryThemer = self.ConnectryThemer || {};
  Object.assign(self.ConnectryThemer, {
    generateThemeCSS,
    renderFavicon,
    renderTheme,
    defaultFaviconForTheme,
    hexToRgb,
    FAVICON_ICONS,
    FAVICON_DEFAULT_CONFIG,
  });

  // Compat shim: old API surface exactly as core/favicon/engine.js exposed it.
  // Mark with _loaded so a re-load is idempotent.
  const compat = (self.ConnectryFavicon = self.ConnectryFavicon || {});
  if (!compat._loaded) {
    compat._loaded = true;
    compat.ICONS = FAVICON_ICONS;
    compat.DEFAULT_CONFIG = FAVICON_DEFAULT_CONFIG;
    compat.THEME_ICON_MAP = {};
    compat.defaultForTheme = defaultFaviconForTheme;
    compat.buildSVG = renderFavicon;
  }
}


// Export for Node (CI preset rebuild, tests) + background.js service worker.
if (typeof module !== 'undefined') {
  module.exports = {
    generateThemeCSS,
    renderFavicon,
    renderTheme,
    defaultFaviconForTheme,
    hexToRgb,
    FAVICON_ICONS,
    FAVICON_DEFAULT_CONFIG,
  };
}
