#!/usr/bin/env node
/**
 * render-presets.mjs — Pre-render every preset theme's artifacts from the
 * canonical engine. Run this manually (or have CI run it) whenever
 * themes/engine.js, themes/derive.js, themes/color-utils.js, or
 * themes/themes.json changes.
 *
 * Outputs:
 *   content/themes/<id>.css    — the theme's full rendered CSS
 *   content/favicons/<id>.svg  — the theme's favicon SVG
 *
 * Each output file is stamped with an AUTOGENERATED header so a drift check
 * can assert no file has been hand-edited. CI (.github/workflows/render-presets.yml)
 * runs this script on every relevant push and fails the build if git detects
 * a diff against checked-in files — forcing authors to regenerate locally
 * before pushing. Drift-free by construction.
 *
 * Part of Migration A2 (ARCHITECTURE.md §V2.5). This script is the CI piece
 * that lets the engine stay Studio-side while the binary ships deterministic
 * data.
 *
 * Usage:
 *   node scripts/render-presets.mjs
 */

'use strict';

import { createRequire } from 'node:module';
import { writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(__dirname, '..');
const require = createRequire(import.meta.url);

const engine = require(resolve(REPO, 'themes/engine.js'));
const themes = require(resolve(REPO, 'themes/themes.json'));

const THEMES_OUT = resolve(REPO, 'content/themes');
const FAVICONS_OUT = resolve(REPO, 'content/favicons');

// Handwritten preset CSS exceptions (A2 climbdown, 2026-04-16): seven
// curated preset CSS files pre-dated A2 and were field-tested against
// Salesforce's Aura DOM. When render-presets.mjs regenerated them from
// the engine, they grew ~500 lines each — which caused Chrome to stall
// on theme-switch (recalculate-style + layout on thousands of Aura
// elements). Keeping the handwritten versions for these 7 themes.
// The other 10 preset themes had no handwritten files before A2 — they
// were engine-rendered at install time by background.js — so their
// engine output IS the canonical CSS and gets regenerated here.
//
// Favicons for the handwritten 7 are STILL regenerated (small, safe).
// If the engine's CSS-gen ever gets a performance-conscious refactor,
// clear this list and the drift detector exception.
const HANDWRITTEN_CSS_SKIP = new Set([
  'arctic', 'connectry', 'connectry-dark', 'midnight', 'obsidian', 'slate', 'tron',
]);

for (const dir of [THEMES_OUT, FAVICONS_OUT]) {
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
}

function cssHeader(themeId) {
  return `/*
 * AUTOGENERATED by scripts/render-presets.mjs — DO NOT EDIT BY HAND
 *
 * Source:   themes/themes.json  (id: "${themeId}")
 * Engine:   themes/engine.js  (renderTheme)
 *
 * To regenerate all preset artifacts:
 *   node scripts/render-presets.mjs
 *
 * CI enforces every preset CSS matches current engine output. See
 * .github/workflows/render-presets.yml — edits here lose on the next
 * push that touches themes/engine.js.
 */
`;
}

// SVG autogen hints need to live in the SVG comment syntax (<!-- -->) so
// browsers parse the file cleanly as an image.
function svgHeader(themeId) {
  return `<!-- AUTOGENERATED by scripts/render-presets.mjs — source: themes/themes.json (${themeId}) — engine: themes/engine.js -->\n`;
}

let rendered = 0;
const errors = [];

let cssSkipped = 0;
for (const theme of themes.themes || []) {
  if (!theme?.id) continue;
  try {
    const { css, faviconSvg } = engine.renderTheme(theme);
    const svgPath = resolve(FAVICONS_OUT, `${theme.id}.svg`);
    writeFileSync(svgPath, svgHeader(theme.id) + faviconSvg, 'utf8');

    if (HANDWRITTEN_CSS_SKIP.has(theme.id)) {
      cssSkipped++;
    } else {
      const cssPath = resolve(THEMES_OUT, `${theme.id}.css`);
      writeFileSync(cssPath, cssHeader(theme.id) + css, 'utf8');
    }
    rendered++;
  } catch (err) {
    errors.push({ id: theme.id, err: err.message });
  }
}

console.log(`✓ render-presets: ${rendered}/${(themes.themes || []).length} themes rendered`);
console.log(`  CSS out: ${THEMES_OUT}  (${cssSkipped} handwritten CSS preserved)`);
console.log(`  SVG out: ${FAVICONS_OUT}`);

if (errors.length) {
  console.error('\n✗ errors:');
  for (const e of errors) console.error(`  [${e.id}] ${e.err}`);
  process.exit(1);
}
